### PR TITLE
Bundle Update on 2016-04-04

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [coursemology-polyglot](https://github.com/Coursemology/polyglot), [0.2.2...0.2.3](https://github.com/Coursemology/polyglot/compare/v0.2.2...v0.2.3) ([CHANGELOG](https://github.com/Coursemology/polyglot/releases))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
41 Pull Requests sent and 4 hours, 25 minutes, and 51 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by lowjoel** [comment]
@fonglh @allenwq Gotta do some database hackery. Before deploying this new version, change the JavaScript record to be that casing, instead of all lowercase, otherwise... app won't boot.

**Comment by allenwq** [comment]
I fixed production already, but don't have access to staging now. @fonglh Can you do that for staging ?

**Comment by fonglh** [comment]
You mean `JavaScript`?

**Comment by fonglh** [comment]
Fixed in staging.

**Pull request merged**
