### PR TITLE
Show test case output to staff.

### LINKED ISSUE #1461: Display test case failure message to graders
In v1, graders can see the expected and actual output when grading missions.

In v2, the unittest framework captures differing output in a `failure` tag in the report file. Store this with the grading result and display it to the grader.

### LINKED ISSUE #1499: Display actual output of test cases
Show tutors actual output of running the test cases when grading student submissions.

This depends on the `output` attribute of the custom `meta` tag in the test report.

Depends on #1463.

### PR DESCRIPTION
**Pull request by fonglh**
If there is no output attribute, fallback to failure message, error
message, then empty string.

Hide hint when submission is not being attempted.

Fixes #1461, fixes #1499.

screen shot 2016-09-20 at 2 38 28 pm

### CODE REVIEW

**Comment by kxmbrian** [comment]
LGTM. 

Possible enhancement is to use different font colour for failure/error case and maybe DRY up `_test_cases.html.slim` once things have stabilized. @allenwq mentioned that cancancan checks are costly, so maybe avoid repetition of `can?(:grade, answer.answer)`.

**Comment by fonglh** [comment]
Ok will work on colour display in a separate PR.

I'll like to DRY up the file too, maybe can put some of the test case extraction logic in a helper.

**Comment by weiqingtoh** [comment]
You can do `gradable = can?(:grade, answer.answer)` then use that in the template. 

Also, _test_cases is really quite hard to read >_< Maybe create a issue and address it soon? 

Otherwise, do we need to add a spec for this?

**Comment by fonglh** [comment]
Created #1515 and #1514. If this is ok then merge first?

Specs were already added for the data storage in #1469.

**Comment by weiqingtoh** [comment]
@fonglh the specs I'm referring to is on helper, or can be written as a feature spec - you have some inherent display logic in `#get_output`. If I wanted to refactor with no spec, I might be doing it wrongly.

**Comment by fonglh** [comment]
Hound fixed. Outdated diffs not hidden.

**Pull request merged**
