### PR TITLE
Add pry and byebug for a better debugging experience

### PR DESCRIPTION
**Pull request by jsyeo**
lol

### CODE REVIEW

**Comment by wangqiang1208** [comment]
:+1:

**Comment by lowjoel** [comment]
No, I'm against this. These should be installed globally as a decision that you as a developer make.

Not to mention this adds the likelihood of slipping debug statements in.

**Comment by jsyeo** [comment]
> These should be installed globally as a decision that you as a developer make.

I may `gem install pry` but when I do `rails c` I don't get pry. I get irb instead.

**Comment by lowjoel** [comment]
You'll probably need to add a pry loader to the rails loader script.

And if you're using rubymine you should be using the built-in debugger gem...

**Comment by jsyeo** [comment]
Okay... :confused:

**Pull request closed without merging**
