### PR TITLE
Survey UI tweaks

### LINKED ISSUE #2186: Survey results to allow wordwrap for text overflow instead of ellipsis
Survey responses that are too long are now overflow:hidden and hence, cannot be read further. Need to change it to wordwrap for overflow cases.

### PR DESCRIPTION
**Pull request by kxmbrian**
Fixes #2186 - previously, user can only see long text responses if s/he hovers over the truncated text long enough.

### CODE REVIEW

**Comment by weiqingtoh** [comment]
2 questions: 
 1. Should we use ExpandableText here?
 2. I'm not sure of the context here, but since there are UI fixes to the response, does it make sense to filter out the blank text responses (or nil responses)? We can discuss offline if there is other considerations which I have left out.

**Comment by kxmbrian** [comment]
Thanks @weiqingtoh and @allenwq for the discussion. The latest commit makes the following changes to the survey results page:
- Ensure no text is truncated with ellipses
- Adjust column widths for multiple choice and multiple response questions with no images
- Limiting the height of each question by adding a scroll bar makes scrolling between questions troublesome since mouse must be off a question, e.g. on the sidebar, before user can scroll. Changed this so that long question result cards are collapsed by default and user can expand the results using a "show all responses/options" button.
- Added some tests

screen shot 2017-03-29 at 8 16 42 pm

**Comment by allenwq** [comment]
LGTM. 

@kxmbrian some other issues to fix:
- The nil responses are displayed as `NIL` now.
- We should show a loader before the results is loaded, now the results page takes quite some time to load, should at least let the user know that we are loading resources.

**Comment by weiqingtoh** [comment]
> We should show a loader before the results is loaded, now the results page takes quite some time to load, should at least let the user know that we are loading resources.
Is there a way to do this globally for all react components?

**Comment by kxmbrian** [comment]
> The nil responses are displayed as NIL now.

The "Nil"s that you see are entered by students

> We should show a loader before the results is loaded, now the results page takes quite some time to load, should at least let the user know that we are loading resources.

Have cleared some debt and ensured that loading messages are added for all survey pages.

> Is there a way to do this globally for all react components?

Do you mean that we could have a single `isLoading` flag for the whole react app? There are potentially multiple fetches that we want to track separately. In the context of surveys, it is possible for this sequence of events:

1. Student navigates to Survey Show page. (Single) Survey loading starts.
2. Student navigates to Survey Index page before (single) survey loading ends. (Full list of) Surveys loading starts.
3. (Single) survey loading ends. `isLoading` flag is set to false even though loading for current page (i.e. Survey Index page) has not completed.

**Comment by allenwq** [comment]
@weiqingtoh the parent component is loaded and displayed, but it still needs extra data to display sub-components. I think we cannot not do this globally as different pages will behave differently. The correct thing to do is to update the UI to show loading bar before we file the request to the server, and update the UI again to show the data after we get the data from server.

**Comment by allenwq** [comment]
> The "Nil"s that you see are entered by students
@kxmbrian There's quite some capital `NIL` in the responses, I am surprised that students enter so consistently ><

**Comment by weiqingtoh** [comment]
Maybe I should have been a little clearer - was thinking whether we could have a component wrapper to handle this (or any other way of solving it), then wrap it over other components. Having a global `isLoading` is possible but if there are multiple subcomponents it wouldn't work. 

Following @allenwq's suggestion is probably right - let the different pages handle this.

**Comment by allenwq** [comment]
@kxmbrian Shall we follow the material design and display a loading indicator instead of text message ? http://www.material-ui.com/#/components/refresh-indicator 

I think it's also easier for us since we don't need to handle translation 😄

**Pull request merged**
