### PR TITLE
Enable scss checks on hound

### PR DESCRIPTION
**Pull request by jsyeo**
lol

### CODE REVIEW

**Comment by lowjoel** [comment]
can you help remove the linter from Travis, and then check that they've got sane SCSS defaults (a la our .unhound.yml...)

**Comment by lowjoel** [comment]
And also from #81, wrt https://github.com/causes/scss-lint/blob/master/config/default.yml, there's some configuration options for naming.

We might want to change this to follow Winston's rails_utils (controller is underscored), selectors are dasherised. So a regex for valid identifiers would be in order.

**Comment by jsyeo** [comment]
> We might want to change this to follow Winston's rails_utils (controller is underscored), selectors are dasherised

I am not so sure about using underscored selectors in our css. :confused: Nevertheless, I sent in a PR to rails_utils :point_right: https://github.com/winston/rails_utils/pull/13

**Comment by jsyeo** [comment]
> check that they've got sane SCSS defaults (a la our .unhound.yml...)

Seems sane to me.

**Pull request merged**
