### PR TITLE
Video graph player

### PR DESCRIPTION
**Pull request by yichenshen**
Adds a video player to the page with the graphs, and allows users to click on the graph to jump around the video.

The charts can now just read the duration off the player.

### CODE REVIEW

**Comment by weiqingtoh** [comment]
LGTM. I have 2 comments: 
 - Is it possible to add some padding to the bottom of the `Statistics` component so that there is some whitespace to see the comments? 
 - As a student I can view my own video submission events/statistics (but not other student's submissions). Is this intended?

**Comment by yichenshen** [comment]
> Is it possible to add some padding to the bottom of the Statistics component so that there is some whitespace to see the comments?

Ok, added a 30px padding.

> As a student I can view my own video submission events/statistics (but not other student's submissions). Is this intended?

I'm not 100% sure about this. Cancancan won't allow a student to create a new video session unless he has read access to his own submission (since session belongs to submission). Currently, there's no way for a student to click into that screen, but he can get there if he knows the URL.

I don't see a huge problem with a student having access to his own statistics, as long as he can't access another student's.

**Comment by weiqingtoh** [comment]
> I'm not 100% sure about this. Cancancan won't allow a student to create a new video session unless he has read access to his own submission (since session belongs to submission). Currently, there's no way for a student to click into that screen, but he can get there if he knows the URL.

Have you checked with Prof Ben on this?

In the worst case I think there is a way to allow creation but not access/read/view (using `can :create Video::Session` and `cannot :read Video::Session`).

**Comment by yichenshen** [comment]
> In the worst case I think there is a way to allow creation but not access/read/view (using can :create Video::Session and cannot :read Video::Session).

I think disabling that won't help since it's rendered in the Submission Controller.

Actually, do you think adding `authorize!(:manage, @video)`, just like in the `index` action in the same controller works? They should have the same permissions anyway.

**Comment by weiqingtoh** [comment]
I'm working on a new `CourseUser` role called Course Observer, which might need to have read permissions (but not write to videos). Suggest we can add an additional `authorize` but not on `manage`, perhaps read on video submissions?

**Comment by weiqingtoh** [comment]
@yichenshen Sorry any updates on this?

**Comment by yichenshen** [comment]
Ah so sorry, have been busy over CVWO and almost forgot.

Iirc students currently also have read permissions on submission, since just loading the resource itself checks `can? :read`. If we need it both ways we probably need a custom permission, like `:analyze` maybe?

I'll try to see if I can get sometime out by the end of the week?

**Comment by yichenshen** [comment]
@weiqingtoh I added an `:analyze` ability to video submissions and authorized it on the submission index and show pages (where the graph is shown). The ability is given to all staff but not users.

**Comment by yichenshen** [comment]
@weiqingtoh any updates? I rebased it.

**Comment by weiqingtoh** [comment]
Sorry, have been a little busy lately - LGTM, will merge!

**Pull request merged**
