### PR TITLE
Implement frontend for online editor

### PR DESCRIPTION
**Pull request by justwudi**
Last step of #1568
Depends on #1834 

This PR:

- Implements the python editor using ReactJS and material-ui.
  + Validates the presence of at least 1 test case when autograded is checked.
  + When the assessment is autograded, the question cannot be set to non-autograded.
- Implements adding and deleting data files for python editor.
  + If the user adds a new file with the exact same filename as an existing file, the new file will automatically replace the existing file even if the user did not mark the existing file for deletion.
- Display the user who last modified the package file/last edited the python editor.

### CODE REVIEW

**Comment by allenwq** [comment]
@justwudi 

Currently if the package is invalid, user will lost his inputs in the template.  
Can you you also track the job ( button will display 'evaluating' ) when creating the question ?  so that there's no redirection and user input can possibly be saved upon failure.
There are also some UI issues, I will discuss with you on slack.

**Comment by fonglh** [comment]
Add a newline between student code and `append.py`, else there'll be a confusing syntax error if the student doesn't end his code with a newline.

The same thing might have to be done with `prepend.py`

**Comment by fonglh** [comment]
The easiest way to do this is probably to just add a comment line to `append.py` when generating the package.

Can fix in another PR cos this isn't a frontend issue.

**Comment by allenwq** [comment]
@justwudi 👍  Thanks ! You can fix the issue that @fonglh mentioned in a later PR. Also we need more specs on the package generation service.

**Pull request merged**
