### PR TITLE
Remove unnecessary line from course/user_invitations_controller.rb

### PR DESCRIPTION
**Pull request by dexterleng**
Tests seem to pass without it.

### CODE REVIEW

**Comment by fonglh** [comment]
Check the failing spec and see if that scenario still works.

**Comment by dexterleng** [comment]
`rspec ./spec/features/course/invitation_management_spec.rb` fails on the master branch too.

**Comment by fonglh** [comment]
Doesn't fail for me. Paste your test output here.

**Comment by fonglh** [comment]
Closing this. Just verified that the line is necessary and removing it causes a change in the UI as caught by the failing test.

To reproduce, try adding users individually in a course. Without building the invitation first, the first row of blank text boxes does not appear.

**Pull request closed without merging**
