### PR TITLE
Rename tutor to a more general name (instructors) for student statistics

### PR DESCRIPTION
**Pull request by weiqingtoh**
Minor fix to make the terms used a little more generic.

### CODE REVIEW

**Comment by allenwq** [comment]
Not sure if we want to rename "tutor" to "instructors". in the course home page, "instructors" are referring to lecturers.

@fonglh @kxmbrian any thoughts ?

**Comment by weiqingtoh** [comment]
The other way would be to work all these terms out at 1 go - define terms for `course_owner`, `course_manager` and `course_staff`. The issue is that different context uses different terms (university vs secondary schools - ie. teachers vs lecturers & tutors). Hence, was thinking that instructor is a good term that is able to achieve both context.

We can help to clarify some of this, and maybe get @michelletan 's opinion as well?

**Comment by kxmbrian** [comment]
Agree that "tutor" is not very suitable in the context of schools (thinks tuition centres >_<). I think "instructor" is better, but might not be a good fit in say the case where the named staff member only grades assignment, like in CS1010X. The "Staff Stats" page uses "Staff Name" as the column header. How about if we use "Staff" for both headers?

**Comment by fonglh** [comment]
I think "Staff" for both is fine. Everyone should know who the main instructor is and who are his assistants.

Or maybe "Instructor" and "Assistants".

**Pull request closed without merging**
