### PR TITLE
Always show delete button column for levels index view

### PR DESCRIPTION
**Pull request by kxmbrian**
Remove one unnecessary ability check

### CODE REVIEW

**Comment by weiqingtoh** [comment]
Actually I put this in because I don't want course owners to delete the default level. This default level is implicit for getting current_level + level#next

**Comment by kxmbrian** [comment]
Does the cancancan ability already guard against this? 
There is already a `can?` check on the button itself. Is that enough?

**Comment by weiqingtoh** [comment]
Oh I see - sorry misread this as removing the immediate delete button :+1:

**Comment by lowjoel** [comment]
Wait, I just thought about it.

The levels partial has that check, right? Now when a user cannot delete that level the row only has 2 columns.

You need to also change the levels partial to move the `if can?` into the th.

**Comment by kxmbrian** [comment]
@lowjoel You mean move it into the `td` right? 
Fixed in #930

**Pull request merged**
