### PR TITLE
Use a helper instead of a service to find tutors of a student

### PR DESCRIPTION
**Pull request by kxmbrian**
Follow up for #1341

### CODE REVIEW

**Comment by weiqingtoh** [comment]
Actually can we put this in a concern in the models instead? Since it doesn't deal directly with view display, but rather model search logic.

**Comment by fonglh** [comment]
I think @weiqingtoh's suggestion makes sense. It's to get data in some other form from the model.

**Comment by kxmbrian** [comment]
I did something like`CourseUser#my_students` initially, but decided to factor it out to avoid N+1. Since this straddles Groups, GroupUsers and CourseUsers, I considered doing a `Course::Group::DirectoryService` instead so that you can look up tutors, my_students, teammate etc while avoiding N+1. @allenwq felt we should refactor to that only when the need arises.

Putting it in the model is probably still workable, just that we'll have to do something like `student1.all_tutors(@tutors)` instead of `student1.all_tutors`. @allenwq what do you think?

**Comment by allenwq** [comment]
This logic belongs to Model layer of MVC, but I believe this should be someting beyound rails model, and it's actually used for picking up already queried results to avoid N + 1. Use `student.all_tutors(@tutors)` will work but it's not intuitive and I will ask why not use `student.tutors`.

So I suggested @kxmbrian using a service to create the statistics, but current way still couples the service with the view which is not what I want.

What I will do is something like:
```ruby
# controller
@stats = StudentStatisticService.new(course).call

# view
@stats.each do |stat|
  # stat is an obect which holds the data view wants
  exp: stat.exp
  tutor: stat.tutors
```

Doing it this way even we changed the front end to JS or something else, it requires little modification to the backend.
That's also how I will refator the staff summary. 

Think futher, I am actually looking into this gem: https://github.com/drapergem/draper

What you guys think ? We can discuss later in the meeting too.

**Comment by weiqingtoh** [comment]
There are some pages where quite some logic is required (especially when it spans over various models) - probably placing them as services or decorators might make more sense. But between decorators and service, I'm not sure which would be more suitable for our use case >_<

**Pull request closed without merging**
