### PR TITLE
Change max time limit for programming question to 300 seconds

### PR DESCRIPTION
**Pull request by ekowidianto**

### CODE REVIEW

**Comment by ekowidianto** [comment]
@cysjonathan Perhaps, do we want to create a setting in the assessment component to set the max timeout? We can default it to 5 seconds and let users change up to 30 seconds.

**Comment by cysjonathan** [comment]
> We can default it to 5 seconds and let users change up to 30 seconds.

5 seconds default probably too short and cause degraded experience to existing questions.
Choosing 10 or 20s is also a bit arbitrary, best to leave the default as the current 30s.

**Review by cysjonathan — APPROVED** [review]
LGTM thanks for spotting the spec file.

**Comment by cysjonathan** [comment]
For discussion, the current solution is a straightforward increase of the max timeout from 30s to 300s throughout Coursemology.

Before we add in more fine-grained control, we should consider these points:

> create a setting in the assessment component to set the max timeout

Concerns
1. Any user who discovers this setting has no reason to lower the max timeout i.e. they will always max it out to the upper limit.
2. Package timeout is originally set to 10s. User lowers course setting max timeout to 5s. Which value takes precedence? Does the 10s get overridden at the DB level to 5s? User then increases course setting max timeout to 20s. If the DB value of the package was reduced from 10 to 5, there is now no way to restore back to original.
3. If we do not override, execution of package now requires a refactor of process to check against the course assessment setting first.
4. If we ignore the course setting during package execution and only validate during create/update/duplication, this causes confusion to the user.

> Can we make this a unique feature that we enable just for our classes?

Concerns:

1. Coursemology currently does not have any "instance-admin-only" level of control at the course level. Perhaps some fields in the course settings can be made to be visible/accessible only to "instance-admin" level. The above concerns (2), (3), (4) still exist, but will be less likely to be adjusted "randomly"/"accidently" since instance-admins will understand impact of such changes.

**Pull request merged**
