### PR TITLE
Add migration to add unique index to multiple response answer options

### LINKED ISSUE #1299: Duplicate MCQ options for a single answer in a submission
Somehow one student managed to submit 2 of the same options for an MCQ question - this results in the autograding service not being able to identify do the auto-grading. 

To investigate how this could happen (One obvious way is to tamper with the forms before submitting the answer).

Possible solutions:
- Create a unique index on `answer_id` and `option_id` in the `course_assessment_answer_multiple_responses` table (Will need to investigate and remove duplicates from production before implementation - possibly can do a rake task to remove them).
- Allow the auto-grader to handle duplicate answers.

### PR DESCRIPTION
**Pull request by weiqingtoh**
Fixes #1299.

### CODE REVIEW

**Comment by fonglh** [comment]
Will this break on migration? i.e. is there non-unique data we need to clean out first?

**Comment by allenwq** [comment]
@fonglh Nope, it will clean the duplicates.

**Comment by allenwq** [comment]
Oops, I thought this is my PR ><

**Comment by fonglh** [comment]
No problem, he's about to use your PR #1346 as a reference for the dedup function.

**Comment by weiqingtoh** [comment]
Forgot about that - updated!

**Pull request merged**
