### PR TITLE
Show access denied page to non course users visiting assessments index

### PR DESCRIPTION
**Pull request by fonglh**
References #1226.

### CODE REVIEW

**Comment by allenwq** [comment]
Assessments also can be accessed before user enter the course ?

**Comment by fonglh** [comment]
It's blank, same as the forum. This 'fix' breaks specs though. I'm waiting to see what's broken.

**Comment by allenwq** [comment]
You should do in `Course::Assessment::Controller` in an before action, just check if user has entered the course, I remember you defined a new ability for that ?

**Comment by fonglh** [comment]
```
def load_and_authorize_assessment
    authorize! :participate, :course
    options = load_assessment_options.reverse_merge(through: :course,
                                                    class: Course::Assessment.name)
    self.class.cancan_resource_class.new(self, :assessment, options).load_and_authorize_resource
  end
```

Just tried this, now got even more authorization test failures. Although the index pages work as expected.

**Comment by allenwq** [comment]
The failures might due to the specs are written wrongly ( using wrong user or sth), you should check why.

**Comment by fonglh** [comment]
Got 100+ of them 😱

**Comment by allenwq** [comment]
Most of them should because the same reason

**Comment by allenwq** [comment]
Should `:course` be `current_course` ?

**Comment by fonglh** [comment]
That works.

Superseded by #1436.

**Pull request closed without merging**
