### PR TITLE
Add eager loading for announcements' read status.

### PR DESCRIPTION
**Pull request by lowjoel**

### CODE REVIEW

**Comment by allenwq** [comment]
@lowjoel Why need to eager load readmarks ?

**Comment by lowjoel** [comment]
untitled

**Comment by allenwq** [comment]
Yah there is a eager load problem, but why readmarks are loaded for each announcement ?

**Comment by lowjoel** [comment]
_announcement.html.slim:
```slim
= div_for(announcement, class: time_period_class(announcement))
  h2
    - if announcement.unread?(current_user)
      small => fa_icon 'envelope'.freeze
```

**Comment by allenwq** [comment]
Okay, I see, it's our code.

**Pull request merged**
