### PR TITLE
Fix all rubocop warnings.

### PR DESCRIPTION
**Pull request by lowjoel**
Why is Coveralls not giving PR statuses :cry:

### CODE REVIEW

**Comment by wangqiang1208** [comment]
@lowjoel @jsyeo  Have we add rubocop in travis ? I didn't see that

**Comment by lowjoel** [comment]
@jsyeo will add it back later.

**Comment by wangqiang1208** [comment]
Should we wait for that ?

**Comment by lowjoel** [comment]
Can merge this first. I've run rubocop over this locally.

**Pull request merged**
