### PR TITLE
Bundle Update on 2016-03-30

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [cancancan-squeel](https://github.com/lowjoel/cancancan-squeel), [0.1.0...0.1.2](https://github.com/lowjoel/cancancan-squeel/compare/v0.1.0...v0.1.2) ([CHANGELOG](https://github.com/lowjoel/cancancan-squeel/blob/master/CHANGELOG.md))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
37 Pull Requests sent and 4 hours, 8 minutes, and 12 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by lowjoel** [comment]
This will break, I need to release 0.1.3.

**Comment by lowjoel** [comment]
@allenwq any comments on that change?

**Comment by lowjoel** [comment]
@allenwq thanks! let's see if beta is now REALLY FAST.

**Comment by allenwq** [comment]
Yep, have we deployed this to production ?

**Comment by lowjoel** [comment]
Waiting for bamboo, I'll tell you...

**Pull request merged**
