### PR TITLE
[1/n] Migration + models for multiple reference timelines

### PR DESCRIPTION
**Pull request by louietyj**
Implements the LHS of the new schema:
image

TODOs:
* Create reference timelines for all existing courses and migrate the data over
* Validations on new tables, e.g. make sure that a course must have at least one reference timeline with reference times for all lesson plan items
* Read/write to new tables

### CODE REVIEW

**Comment by louietyj** [comment]
Not checking in schema.rb at this point while things are still volatile.

**Comment by fonglh** [comment]
Take a look at the rake tasks in `lib/tasks/db`. Those were for migrating answer comments from being parented by the answer to being parented by the new model `Course::Assessment::SubmissionQuestion`. The db migration only created the tables and columns while the much longer running data copying was handled by rake tasks which were run manually.

Perhaps you could do something similar? I'll send you the email thread too for more context.

**Comment by louietyj** [comment]
Yeah the data migration is done in [2/n], right now it's packaged as a migration script but I need to test it on the prod data to see how long it takes before deciding whether it should be a rake task.

Any input on the current [1/n]?

**Comment by louietyj** [comment]
Ok nope it's impossible to do stacked diffs on Github so I'll just close this and reopen when _everything_ is ready.

**Pull request closed without merging**
