### PR TITLE
Implement completely building accessibility relations in Squeel

### PR DESCRIPTION
**Pull request by lowjoel**
This respects multiple joins against the same table.

### CODE REVIEW

**Comment by lowjoel** [comment]
Hmm, I think I'm not applying the rules in the right order...

**Comment by lowjoel** [comment]
@allenwq done! I measured the difference, it's 7 min 5 sec with the gem, 7 min 1 sec using normal cancancan.

**Comment by allenwq** [comment]
@lowjoel 7min 5s is the time of running whole test suite ?

**Comment by lowjoel** [comment]
yeah, entire test suite. I don't know if there is a significant time difference. I didn't run the tests with replicates, so it could just be normal variation...

**Comment by allenwq** [comment]
Just tested some pages with your gem on my local, for those pages almost 10x faster when doing `load_and_authorize_resource`

**Comment by lowjoel** [comment]
@allenwq shall we merge and see if beta can be loaded?

**Comment by lowjoel** [comment]
You can run all specs with and without, and see how it goes also?

**Comment by allenwq** [comment]
Yah, can load already in my local, I'll merge it. Thanks !

**Comment by allenwq** [comment]
@lowjoel But courses index page still not very fast, it takes 1100ms to do `@courses.to_a` in production mode in my local, I have 1 course and 8k users.

**Comment by lowjoel** [comment]
Let's see this and then decide what else needs to be fixed.

**Comment by allenwq** [comment]
Yep, thanks !

**Pull request merged**
