### PR TITLE
Rename #sidebar to #all_sidebar_items

### PR DESCRIPTION
**Pull request by allenwq**

### CODE REVIEW

**Comment by allenwq** [comment]
@lowjoel I think that we still need a better name for `all_sidebar_items` ? This function is actually not 'all items' because the returned items are filtered by `type`

**Comment by lowjoel** [comment]
#sidebar_items? but i'm not sure that symmetry holds.

**Comment by allenwq** [comment]
or `sidebar` and `ordered_sidebar` ?

**Comment by lowjoel** [comment]
Keep it with all_sidebar_items, change the parameter to a keyword argument. `all_sidebar_items(type: :admin)`

**Comment by allenwq** [comment]
OK!

**Comment by allenwq** [comment]
done.

**Pull request merged**
