### PR TITLE
Fix the time_bounded scope.

### LINKED ISSUE #320: currently_valid extension method may return invalid items
These two snippets don't seem to be equivalent. When using currently_valid announcements outside the time range are returned.

```
in_time_range = proc { (valid_from <= Time.zone.now) & (valid_to >= Time.zone.now) }
system = SystemAnnouncement.includes(:creator).where(&in_time_range).order(valid_from: :desc)
```

```
system = SystemAnnouncement.includes(:creator).currently_valid.order(valid_from: :desc)
```

Generated SQL:

```sql
SELECT
    "system_announcements" . *
FROM
    "system_announcements"
WHERE
    (
        "system_announcements" . "valid_from" <= '2015-06-11 01:56:20.055546'
        AND "system_announcements" . "valid_to" >= '2015-06-11 01:56:20.055546'
    )
ORDER BY
    "system_announcements" . "valid_from" DESC
```

```sql
SystemAnnouncement Load (0.4ms)  
SELECT
    "system_announcements" . *
FROM
    "system_announcements"
WHERE
    "system_announcements" . "valid_to" >= '2015-06-11 01:49:37.733670'
ORDER BY
    "system_announcements" . "valid_from" DESC
```

### PR DESCRIPTION
**Pull request by lowjoel**
Fixes #320.

### CODE REVIEW

**Comment by lowjoel** [comment]
@dariusf and @allenwq have a look.

**Comment by dariusf** [comment]
Tried merging this into my branch and I get a test failure [here](https://github.com/Coursemology/coursemology2/blob/master/spec/features/global_announcements_spec.rb#L54-L56).

**Comment by lowjoel** [comment]
@dariusf what branch is that?

**Comment by dariusf** [comment]
dariusf/generic-announcements

**Comment by lowjoel** [comment]
I'm not sure if that's a problem with your branch or...

**Comment by lowjoel** [comment]
Okay, this can be merged @allenwq

**Pull request merged**
