### PR TITLE
Not prefer find over find

### PR DESCRIPTION
**Pull request by wangqiang1208**
Then there is no complain from rubocop anymore

### CODE REVIEW

**Comment by lowjoel** [comment]
@jsyeo I think this has a different meaning.

**Comment by jsyeo** [comment]
I have a PR to fix this. Chill...

**Comment by jsyeo** [comment]
Anyway, this will not fix hound. Hound will still use thoughtbot's config. >_<

**Comment by jsyeo** [comment]
We have #128. This can be closed.

**Comment by wangqiang1208** [comment]
OK.

**Pull request closed without merging**
