### PR TITLE
Use manager instead of course creator in specs

### PR DESCRIPTION
**Pull request by allenwq**
* Creator is actually the default admin (test@example.org). There are some failures due to admin has too many courses under him.

This is a more correct way as it tests the ability of manager instead of admin. And this will further help reduce the random failure.

### CODE REVIEW

**Comment by allenwq** [comment]
Further removed all the admin in course spec. 

And fixed a bug that course manager cannot create tabs/categories in course settings.

**Comment by fonglh** [comment]
Will we encounter the problem of admin having too many courses under him in production?

**Comment by allenwq** [comment]
No, in our test, test@example.org is the creator of all the factories.

**Comment by fonglh** [comment]
What causes the maximum limit?

**Comment by allenwq** [comment]
All your courses are loaded in every page. test@example.org has hundreds of courses under him.

**Pull request merged**
