### PR TITLE
100% coverage

### PR DESCRIPTION
**Pull request by allenwq**
Make coverage 100% before next phase starts :-P

### CODE REVIEW

**Comment by lowjoel** [comment]
I'm actually thinking of removing the index action for the programming evaluations... or using it as some kind of status page. What do you think?

**Comment by allenwq** [comment]
Sure, I was also thinking of removing it, cause it's not used by anyone.

**Comment by allenwq** [comment]
BTW, the status page for the evaluator ? how about removing it for now and implement when we need it ?

**Comment by lowjoel** [comment]
Yeah, I think we can remove it first.

**Pull request merged**
