### PR TITLE
Remove enable flag as checks are enabled by default

### PR DESCRIPTION
**Pull request by jsyeo**
lol

### CODE REVIEW

**Comment by lowjoel** [comment]
...yah, but... how come it's ignoring our config file ah? Like asking us to use `detect` over `find`.

**Comment by jsyeo** [comment]
I don't know leh >_< by right this shouldn't affect

**Comment by lowjoel** [comment]
yah =.= are we able to debug this?

**Comment by jsyeo** [comment]
Can we merge this and I send in a PR to test?

**Pull request merged**
