### PR TITLE
Remove auto_grader role from user management views.

### PR DESCRIPTION
**Pull request by fonglh**
Prevent the role from displaying in the role selection dropdowns in
course user management and instance user management.

### CODE REVIEW

**Comment by fonglh** [comment]
The failing test here doesn't fail locally.

**Comment by allenwq** [comment]
@fonglh The course user management one also need to remove

**Comment by fonglh** [comment]
Yup removed already. Build passes now.

**Comment by weiqingtoh** [comment]
LGTM. @allenwq ?

**Pull request merged**
