### PR TITLE
Reduce the global query overhead

### PR DESCRIPTION
**Pull request by lowjoel**
Two queries are made regardless of page:
 - The instance for the current URL
 - The global/instance announcements

These queries add about ~5ms per page load. I have combined them together so 10ms page load time is shaved off every request.

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq

**Comment by allenwq** [comment]
@lowjoel Is #321 still wanted ?   I almost need to redo that after #331 and #332

**Comment by lowjoel** [comment]
Still necessary.

**Comment by allenwq** [comment]
Yes, but the top 4 PRs got a lot of conflicts now, Next time can we merge them from bottom to top ?

**Comment by lowjoel** [comment]
I'll merge yours later after I check that it's consistent then I'll rebase this.

**Comment by lowjoel** [comment]
oh, okay... thanks

**Comment by allenwq** [comment]
np, I think I'll just do it again this time :)

**Pull request merged**
