### PR TITLE
Test for rails 4.2 compatibility on travis.

### PR DESCRIPTION
**Pull request by jsyeo**
lol

### CODE REVIEW

**Comment by lowjoel** [comment]
...you're just testing, or want this merged?

**Comment by jsyeo** [comment]
Actually i wanted this to be merged...until i discovered the deployment flag.

**Comment by lowjoel** [comment]
a bit hard to maintain so many gemfiles leh...

**Comment by lowjoel** [comment]
especially when we're adding gems like no one's business while bootstrapping.

**Comment by jsyeo** [comment]
Hmmm...yea. Okay then. We first close lo.

**Comment by lowjoel** [comment]
I think we wait for the Squeel and SchemaPlus gems to be compatible with Rails 4.2 then we just migrate all at once.

**Pull request closed without merging**
