### PR TITLE
Bundle Update on 2017-04-03

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [addressable](https://github.com/sporkmonger/addressable), [2.5.0...2.5.1](https://github.com/sporkmonger/addressable/compare/addressable-2.5.0...addressable-2.5.1) ([CHANGELOG](https://github.com/sporkmonger/addressable/blob/master/CHANGELOG.md))
- Updated: [i18n-js](http://github.com/fnando/i18n-js), [3.0.0.rc16...3.0.0](https://github.com/fnando/i18n-js/compare/v3.0.0.rc16...v3.0.0) ([CHANGELOG](https://github.com/fnando/i18n-js/blob/master/CHANGELOG.md))
- Updated: [i18n-tasks](https://github.com/glebm/i18n-tasks), [0.9.12...0.9.13](https://github.com/glebm/i18n-tasks/compare/v0.9.12...v0.9.13) ([CHANGELOG](https://github.com/glebm/i18n-tasks/blob/master/CHANGES.md))
- Updated: [uglifier](http://github.com/lautis/uglifier), [3.1.10...3.1.12](https://github.com/lautis/uglifier/compare/v3.1.10...v3.1.12) ([CHANGELOG](https://github.com/lautis/uglifier/blob/master/CHANGELOG.md))
- Added: [rainbow](https://github.com/sickill/rainbow), [2.2.1](https://github.com/sickill/rainbow/tree/v2.2.1)
- Removed: [term-ansicolor](http://github.com/flori/term-ansicolor), [1.5.0](https://github.com/flori/term-ansicolor/tree/v1.5.0)
- Removed: [tins](https://github.com/flori/tins), [1.13.2](https://github.com/flori/tins/tree/v1.13.2)

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
108 Pull Requests sent and 11 hours, and 22 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by weiqingtoh** [comment]
LGTM, @allenwq?

**Comment by allenwq** [comment]
@weiqingtoh  should we remove `Updated: i18n-js, 3.0.0.rc16...3.0.0 (CHANGELOG)` ?

**Comment by weiqingtoh** [comment]
I was thinking about it - even if there is `3.0.0.rc17`, deppbot will retain `3.0.0` right?

**Comment by allenwq** [comment]
Let's merge this and see their next release then !

**Pull request merged**
