### PR TITLE
Use CourseUser name if available for Course::Discussion::Posts.

### PR DESCRIPTION
**Pull request by fonglh**
Use the CourseUser name if available for notification emails on
comment threads (SubmissionQuestion) and programming annotations.

Programming annotations themselves are actually discussion posts objects so they're also fixed.

### CODE REVIEW

**Comment by weiqingtoh** [comment]
If this piece of logic is repeated a few times, shall we include it as a method within the `post` model instead?

**Comment by fonglh** [comment]
Refactored the change for forum email notifications done in #2734.

Don't merge yet, haven't done manual testing since the refactoring.

**Comment by weiqingtoh** [comment]
Can add a test for the `author_name`?

**Comment by fonglh** [comment]
Added a test, and checked that the names used in the following emails are the CourseUser names:

- [x] Forum replies
- [x] Programming annotations
- [x] Comments on questions

**Pull request merged**
