### PR TITLE
Bundle Update on 2017-05-23

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [autoprefixer-rails](https://github.com/ai/autoprefixer-rails), [7.1.0...7.1.1](https://github.com/ai/autoprefixer-rails/compare/7.1.0...7.1.1) ([CHANGELOG](https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md))
- Updated: [cancancan](https://github.com/CanCanCommunity/cancancan), [1.16.0...1.17.0](https://github.com/CanCanCommunity/cancancan/compare/v1.16.0...v1.17.0) ([CHANGELOG](https://github.com/CanCanCommunity/cancancan/blob/develop/CHANGELOG.rdoc))
- Updated: [devise-multi_email](https://github.com/allenwq/devise-multi_email), [1.0.5...2.0.0](https://github.com/allenwq/devise-multi_email/compare/v1.0.5...v2.0.0) ([CHANGELOG](https://github.com/allenwq/devise-multi_email/blob/master/CHANGELOG.md))
- Updated: [html-pipeline](https://github.com/jch/html-pipeline), [2.5.0...2.6.0](https://github.com/jch/html-pipeline/compare/v2.5.0...v2.6.0) ([CHANGELOG](https://github.com/jch/html-pipeline/blob/master/CHANGELOG.md))
- Updated: [sass](https://github.com/sass/sass), [3.4.23...3.4.24](https://github.com/sass/sass/compare/3.4.23...3.4.24) ([CHANGELOG](https://github.com/sass/sass/blob/stable/doc-src/SASS_CHANGELOG.md))
- Updated: [spring](https://github.com/rails/spring), [2.0.1...2.0.2](https://github.com/rails/spring/compare/v2.0.1...v2.0.2) ([CHANGELOG](https://github.com/rails/spring/blob/master/CHANGELOG.md))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
117 Pull Requests sent and 13 hours, 12 minutes, and 47 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by weiqingtoh** [comment]
Will lock devise-multi_email until https://github.com/allenwq/devise-multi_email/pull/15 is merged.

**Comment by joelvh** [comment]
hi @weiqingtoh could you give feedback on any regressions or issues you ran into? Would appreciate any observations or tests that need to be added.

Thanks!

**Comment by weiqingtoh** [comment]
@joelvh the version changes actually require us to make a small change, but I thought it would be better for me to do that once your PR is merged as I see significant changes to the gem and prefer not to do unnecessary work for now.

If there is any feedback, I'll let @allenwq know as we work on the same team. Thanks for reaching out!

**Comment by joelvh** [comment]
ok, thanks @weiqingtoh - good to know :-)

**Comment by allenwq** [comment]
@joelvh Really appreciate your contribution and quick response, I will review and test your PR ASAP.

**Pull request merged**
