### PR TITLE
Fix Programming Question form wrong maximum grade validation

### PR DESCRIPTION
**Pull request by purfectliterature**
Reported by Rollbar [#2488](https://app.rollbar.com/a/coursemology/fix/item/Coursemology2/2488/).

### CODE REVIEW

**Comment by ekowidianto** [comment]
Just wondering why does the request url is reported as ‘https://coursemology.org/users/sign_up/completed’ in rollbar?

**Comment by purfectliterature** [comment]
> Just wondering why does the request url is reported as `https://coursemology.org/users/sign_up/completed` in rollbar?

Those are reporting different errors. The error messages for those occurrences are `Timeout` or `Timeout (u)`. You can view all occurrences in Rollbar and go to the last page (the earliest occurrences) and you'd see the maximum grade validation errors from the programming question form.

For some reasons, Rollbar grouped these unrelated occurrences together.

@ekowidianto

**Comment by ekowidianto** [comment]
Got it! What triggered the timeout error tho? @purfectliterature

**Comment by purfectliterature** [comment]
> Got it! What triggered the timeout error tho?

@ekowidianto Not sure. I wasn't able to replicate, and there's not enough information about what exactly timed out. I'd suspect it's some issues at the gateway.

**Pull request merged**
