### PR TITLE
Add a sidebar helper that can be used in views.

### PR DESCRIPTION
**Pull request by lowjoel**
Within the provided block, each sidebar element can be defined using `li`.

### CODE REVIEW

**Comment by lowjoel** [comment]
Stuff like that are getting harder and harder to test. Hahaha. Let me straighten out the other PRs then come back to this.

**Comment by jsyeo** [comment]
@lowjoel, so is this good to merge?

**Comment by lowjoel** [comment]
@jsyeo let me write specs for the helper.

**Comment by lowjoel** [comment]
@jsyeo I think this works.

**Comment by lowjoel** [comment]
I'm starting to wonder if this should be a Slim helper instead. Thoughts?

**Comment by wangqiang1208** [comment]
What do you mean by slim helper ? Inject slim library ?

**Pull request merged**
