### PR TITLE
Bundle Update on 2016-06-02

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [autoprefixer-rails](https://github.com/ai/autoprefixer-rails), [6.3.6.1...6.3.6.2](https://github.com/ai/autoprefixer-rails/compare/6.3.6.1...6.3.6.2) ([CHANGELOG](https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md))
- Updated: [jbuilder](https://github.com/rails/jbuilder), [2.4.1...2.5.0](https://github.com/rails/jbuilder/compare/v2.4.1...v2.5.0) ([CHANGELOG](https://github.com/rails/jbuilder/blob/master/CHANGELOG.md))
- Updated: [kaminari](https://github.com/amatsuda/kaminari), [0.16.3...0.17.0](https://github.com/amatsuda/kaminari/compare/v0.16.3...v0.17.0) ([CHANGELOG](https://github.com/amatsuda/kaminari/blob/master/CHANGELOG.rdoc))
- Updated: [migration_comments](https://github.com/pinnymz/migration_comments), [0.3.2...0.4.1](https://github.com/pinnymz/migration_comments/compare/v0.3.2...v0.4.1)
- Updated: [parser](https://github.com/whitequark/parser), [2.3.1.0...2.3.1.1](https://github.com/whitequark/parser/compare/v2.3.1.0...v2.3.1.1) ([CHANGELOG](https://github.com/whitequark/parser/blob/master/CHANGELOG.md))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
61 Pull Requests sent and 5 hours, 58 minutes, and 30 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq try relaxing the schema_plus_dev (or was it core?) requirement in Gemfile, we were blocked by migration_comments previously.

**Comment by allenwq** [comment]
```
schema_plus_association_inverses (>= 0.0.3) was resolved to 0.0.5, which depends
on
      schema_plus_core (>= 0.3.1, ~> 0.3)
```

@lowjoel it was blocked by schema_plus_association_inverses

**Comment by lowjoel** [comment]
Hmmmm. OK, I'll merge this, then relax the association inverses constraint.

**Comment by lowjoel** [comment]
@allenwq wait, no it's not blocked. `~> 0.3` allows any 0.x version of schema_plus_core.

**Comment by lowjoel** [comment]
Sorry, it's the `schema_monkey` gem.

**Comment by allenwq** [comment]
schema_core released 1.0 version already, I was referring to that.

**Comment by lowjoel** [comment]
@allenwq Oh, OK. I just pushed v0.1.0

**Comment by lowjoel** [comment]
@allenwq also, aha-app/calculated_attributes#11. I've removed my fork.

**Pull request merged**
