### PR TITLE
Fix programming editor answer view.

### PR DESCRIPTION
**Pull request by ekowidianto**
**Issue**

The view only code editor found in the 'view history' of a programming question renders HTML elements for an assessment that has not been finalized. 

Upon further investigation, this is caused by the code content not being highlighted, when being sent from the backend, before it is passed to the ReadOnlyEditor. 

**Solution**

To solve this, we send both highlighted and non-highlighted code contents from the backend and pass the contents to the correct editors respectively.

This PR solves #3760

### CODE REVIEW

**Comment by ekowidianto** [comment]
Similar to PR 4037, the test works locally but fails in CircleCI

**Comment by zhuhanming** [comment]
I think it's not very clear (to me, at least) what is the difference between `content` and `highlighted_content`. Is it possible to name it something more semantic, or include some comments explaining the significance if this is as semantic as it can get?

**Comment by ekowidianto** [comment]
> I think it's not very clear (to me, at least) what is the difference between `content` and `highlighted_content`. Is it possible to name it something more semantic, or include some comments explaining the significance if this is as semantic as it can get?

Actually it's explained in the highlight_code_block function: "This filter will normalise all line endings to Unix format (\n) for use with the Rouge". We could change the term to something else, but I am currently following the existing term in the codebase.

**Comment by zhuhanming** [comment]
Ok, looks good to me! Thanks Eko for the fix!

**Pull request merged**
