### PR TITLE
Change Video comments' editor

### PR DESCRIPTION
**Pull request by yichenshen**
Changed from Summernote to a regular text field. This change makes the
formatting for video comments similar to that of assessment comments.

Context is that we want `<code></code>` formatting in video comments.

Tested on old comments entered by Summernote. As long as old comments do not have complex elements like a full table, the difference is minimal. (Unfortunately the old `<code></code>` are already escaped, so we can't do anything here.

The `<p>` tags inserted by summernote however, will show up in the comment edit field. I feel that it's an okay compromise since I expect edits on old comments to be minimal, but I'm open to suggestions.

### CODE REVIEW

**Comment by fonglh** [comment]
You can convert the existing comments in a migration.

See https://github.com/Coursemology/coursemology2/blob/master/db/migrate/20171024074942_convert_autograded_text_response_answers_to_plaintext.rb

**Comment by yichenshen** [comment]
Nice, ok will do.

**Comment by yichenshen** [comment]
@fonglh I added the migration but replaced the line breaks manually since there are some comments that made use of paragraphing.

**Comment by fonglh** [comment]
After the migration, text enclosed in `<code>` tags will literally be surrounded by the code tags. Is this the intended behaviour?

Same for `<b>` tags, and probably other HTML tags too.

**Comment by yichenshen** [comment]
I intend to keep some of the basic formatting ones such as `<b>` and `<code>` for example so that if they're inserted by summernote they'll stay that way. That's the rationale behind the `Sanitize::Config::BASIC`. From what I tried, actual inserted comments right now surrounded by <code> tags already have their brackets escaped by summernote, and after migration should remain that way.

There's one here: https://coursemology.org/courses/1225/videos/201/submissions/2708/edit?scroll_to_topic=43

**Pull request merged**
