### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by lowjoel**
- Fix Rubocop lints
 - Simplify some functions
 - Break up some large classes

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq might want to check this one commit at a time.

**Comment by lowjoel** [comment]
@allenwq maybe I should to change the fail to raise?

**Comment by allenwq** [comment]
@lowjoel, Changing fail to raise now is fine, rubocop don't have complains right ?

**Comment by lowjoel** [comment]
Yes, but Hound is still using 0.36, which will complain about using raise instead of fail.

**Comment by allenwq** [comment]
I think it's OK, after it was merged we won't see hound's complain :)  Otherwise, rubocop will complain every time when we run it.

**Pull request merged**
