### PR TITLE
Add role to EnrolRequest

### PR DESCRIPTION
**Pull request by kxmbrian**
This is to prepare for #1843 and for migration of v1 EnrolRequests.

### CODE REVIEW

**Comment by weiqingtoh** [comment]
Can we set the default in the model file to be `student`?

**Comment by kxmbrian** [comment]
On further investigation, it appears that v1's EnrolRequest role only takes the values `student` or `observer` only. We don't have an observer role for v2 and the feature is broken on v1. https://github.com/Coursemology/migration/issues/26

Closing this PR for now.

**Comment by weiqingtoh** [comment]
@kxmbrian can we still support this then? Since it is a functionality we need?

**Comment by kxmbrian** [comment]
Will need to add `role` to the UserInvitation model instead

**Pull request closed without merging**
