### PR TITLE
Change default course logo to svg format

### PR DESCRIPTION
**Pull request by weiqingtoh**
Credits to Yanjie for this!

### CODE REVIEW

**Comment by lowjoel** [comment]
wow.

**Comment by lowjoel** [comment]
Yanjie really should go get a Github account. I mean, seriously.

**Comment by fonglh** [comment]
screen shot 2016-02-18 at 8 29 46 am

**Comment by weiqingtoh** [comment]
@luoyj Just for kicks :smiley:

**Pull request merged**
