### PR TITLE
Change turbolinks progress bar colour to red

### LINKED ISSUE #1500: Progress Bar is unclear
Can we please change the colour when progressing to  RED so that it's more clear. Can stay blue when nothing is happening.

### PR DESCRIPTION
**Pull request by kxmbrian**
Fixes #1500

### CODE REVIEW

**Comment by allenwq** [comment]
How to merge ? @fonglh

**Comment by fonglh** [comment]
Should be able to. It says server error on my phone though

**Comment by allenwq** [comment]
I on desktop, it's gray color ><

**Comment by fonglh** [comment]
I think GitHub's approved review check is buggy. I've switched it off.

**Pull request merged**
