### PR TITLE
Small fixes to groups and leaderboard

### PR DESCRIPTION
**Pull request by weiqingtoh**
Arising from #1051 and #1068

### CODE REVIEW

**Comment by weiqingtoh** [comment]
Do we want to fix the nested paranthesis, since it is a DSL? Or should I silence rubocop here?

`cast(coalesce(sum(course_experience_points_records.points_awarded), 0.0).as float)`

**Comment by lowjoel** [comment]
I think we should use the parens, this is a bit unwieldy, just to be sure.

**Comment by weiqingtoh** [comment]
@allenwq and @lowjoel I've added the `TRUE_VALUES` as an extension, would it be better for us to just use this or should I take reference from ActiveRecord instead (`ActiveRecord::ConnectionAdapters::Column`)?

**Comment by lowjoel** [comment]
@allenwq found the other place in AR where the conversion is done... maybe we should use that instead?

**Pull request merged**
