### PR TITLE
`bundle update`

### PR DESCRIPTION
**Pull request by allenwq**
Mainly for devise and schema_validations

### CODE REVIEW

**Comment by lowjoel** [comment]
Do we need to have a new initialiser for schema_validations?

Good work with the gem. What was it supposed to fix?

**Comment by allenwq** [comment]
Not need a new initialiser, the default configuration is fine for us. 

Our existing code don't such issue, I described the issue in detail in this PR:
https://github.com/SchemaPlus/schema_validations/pull/29

**Comment by lowjoel** [comment]
@allenwq surely there was something you were trying to do and you hit that bug right? :stuck_out_tongue:

**Comment by allenwq** [comment]
@lowjoel Yep, when I was doing materials, but that PR no need already. :-P I actually have told you this issue before.

**Comment by lowjoel** [comment]
>.< memory loss already...

never mind, I'm sure that's no longer a problem...

**Comment by allenwq** [comment]
Haha, thanks !

**Pull request merged**
