### PR TITLE
Implement EXP multiplier 

### LINKED ISSUE #1413: Implement EXP multiplier
Provide a multiplier for adjust EXP

### LINKED ISSUE #1415: Autofill EXP when mission submissions are graded
The grading is filled in, but no experience points are awarded

### PR DESCRIPTION
**Pull request by allenwq**
This will fix #1413

The first commit also fixes  #1415 

screen shot 2016-09-01 at 6 15 25 pm

### CODE REVIEW

**Comment by fonglh** [comment]
If the exp is manually modified, it might go out of sync with the multiplier? What happens on the subsequent pageload since the multiplier isn't stored in the db?

**Comment by allenwq** [comment]
@fonglh Latest update does not calculate the initial value when there's already a value stored.

The multiplier only adopts to auto-calculated EXP, if user manually put the EXP it's not affected.  If there's a page reload, the EXP would be recalculated. Yes, unless the user saves the EXP to db.

**Comment by fonglh** [comment]
So with a manually modified EXP, what's the value in the multiplier field on the next reload? Since it'll probably be out of sync, will that be confusing for the grader?

**Comment by allenwq** [comment]
It's a frontend thing and will be reset to 1.0 if you reload the page. Yah might be a bit confusing, what do you suggest ?  The behavior is same as V1.

**Comment by fonglh** [comment]
I think it's ok to leave it for now.

Perhaps we could have a little visual warning that multiplier no longer matches, maybe just a different colour with a tooltip.

**Pull request merged**
