### PR TITLE
Heartbeat Monitoring for Exams: Beta 2

### PR DESCRIPTION
**Pull request by purfectliterature**
- Add heartbeat worker support for SEB on macOS
- Add heartbeat timeline chart in `SessionDetailsPopup`
- Remove heartbeats table in `SessionDetailsPopup`
- Add OS logo to user agent in `SessionDetailsPopup`
- Add heartbeat relative time in `SessionDetailsPopup`
- Add feature to block accesses from browsers with invalid SUS
- Differentiate the `SessionBlob`s between active (listening, stopped, expired) and idle sessions

### CODE REVIEW

**Comment by ekowidianto** [comment]
@purfectliterature Can help to rebase this PR?

**Comment by purfectliterature** [comment]
@ekowidianto Done.

**Review by ekowidianto — COMMENTED** [review]
@purfectliterature Thanks for this! Sorry for the late review
- Could you write some tests for both `monitoring_service.rb`?
- Update the date of the migration file to be later than the last one.

**Review by ekowidianto — APPROVED** [review]
Thanks!

**Pull request merged**
