### PR TITLE
Update .gitignore file

### PR DESCRIPTION
**Pull request by weiqingtoh**
Running rspec has generated a lot of files within the `public/downloads` folder - to add directory to gitignore.

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq I think I mentioned something along the lines of moving the public folder when running specs. Did you get a change to look at it?

**Comment by allenwq** [comment]
@lowjoel Yah, we have a discussion regarding that. Seems we have agreed on something ? can't remember the details.

**Comment by lowjoel** [comment]
@allenwq I think we kind of agreed on trying to change the public directory into the tmp folder so it gets ignored.

**Comment by allenwq** [comment]
@lowjoel How about add a symbol link between `tmp` and `public/downloads` during test ? and also use a different folder in test, like `public/tmp`

**Comment by lowjoel** [comment]
Not possible on Windows, symlinks can only be created by admin accounts there.

Would changing the Rails public directory work?

**Comment by allenwq** [comment]
Googled around, seems rails does not provide any way to directly change the public folder. (There are some guys says can modify Rails.application.paths['public'], but it does not work very well as I tested)

Even though we can get it work somehow, we might still need to copy all the assets in public folder to the tmp folder during tests ? ...to me it's a not very elegant way.

**Comment by lowjoel** [comment]
@weiqingtoh I rebased your branch and added my commit.
@allenwq I moved the public directory, only thing that broke was the rendering of /422 and /403. I think this fix is OK, what do you think?

**Comment by allenwq** [comment]
@lowjoel tried the same config but somehow the downloads was not working properly last time ><

Thanks for the fix !

**Comment by lowjoel** [comment]
I was about to tell @weiqingtoh to remove the first commit...

**Comment by lowjoel** [comment]
But I guess there's no harm in ignoring the public download directory.

**Comment by allenwq** [comment]
I think the first commit is OK, in development mode, there are still files create in `public/downloads`

**Comment by lowjoel** [comment]
Yeah, no harm.

**Pull request merged**
