### PR TITLE
[Assessment Password] Schema changes

### PR DESCRIPTION
**Pull request by allenwq**
Rename `password` to `submission_password`
Add a new `password` column, this one is used for assessment password.

It looks like the format of schema.rb changed a lot after `rails db:migrate`, is it outdated? or I did something wrong?  I did a `db:reset` before migration, so the schema should be in the latest state.

### CODE REVIEW

**Comment by weiqingtoh** [comment]
> It looks like the format of schema.rb changed a lot after `rails db:migrate`, is it outdated? or I did something wrong? I did a `db:reset` before migration, so the schema should be in the latest state.

Probably some of the monkey patching from the schemaplus gems got removed when we upgraded to rails 5, causing the `schema.rb` file to be inconsistent with migrations. We might have to somehow invalidate the previous migrations or restore the schema-plus monkey patches to restore the original `schema.rb` file.

**Comment by weiqingtoh** [comment]
Can I suggest instead that we differentiate the fields to `attempt_password` and `session_password`? I think it is more meaningful than `password` and `submission_password`.

**Comment by allenwq** [comment]
> Probably some of the monkey patching from the schemaplus gems got removed when we upgraded to rails 5, causing the schema.rb file to be inconsistent with migrations. We might have to somehow invalidate the previous migrations or restore the schema-plus monkey patches to restore the original schema.rb file.

OK, then I will leave as it is, cause it reflects the latest state.

**Comment by allenwq** [comment]
@weiqingtoh, As discussed, have renamed them to `view_password` and `session_password`

**Pull request merged**
