### PR TITLE
Update evaluation failed message.

### PR DESCRIPTION
**Pull request by fonglh**
Provide other common reasons why evaluation might fail so it's easier
for the TAs to debug.

[ci skip]

### CODE REVIEW

**Comment by allenwq** [comment]
How about:
"Evaluation failed. There might be a syntax error in your code or perhaps it does not execute within the time and memory limits."
@weiqingtoh Any comments ? 

There are certain things we need to deal after this:
1. To give user the actual error for public tests
2. To detect if the code exceeds the memory or time limit and display
3. To think if it's possible to support actual output of the student's solution

**Comment by weiqingtoh** [comment]
Was trying to think of a slightly better sentence - but I think being more factual will work. Would modify @allenwq's one:
> Your code failed to evaluate - please check for syntax errors, and ensure that that your code executes within the time and memory limits.

**Comment by fonglh** [comment]
They can't do anything about the time/memory limits though. It's not shown to them and right now we don't even know how high they should be set.

**Comment by allenwq** [comment]
@weiqingtoh you OK with the current message ?

**Pull request merged**
