### PR TITLE
Fix submission edit page when the assessment's end time is empty

### PR DESCRIPTION
**Pull request by minhtule**

### CODE REVIEW

**Comment by lowjoel** [comment]
I don't see how this is necessary, nil evaluates to false.

**Comment by lowjoel** [comment]
@weiqingtoh already fixed this in #612.

**Comment by minhtule** [comment]
Oops, I saw the other pull request but overlooked the changes while rebasing. Anyway, there is inconsistency in using `present?` or not in the codebase.

**Comment by lowjoel** [comment]
present? is not the opposite of nil?

**Comment by minhtule** [comment]
Then #530 should be fixed to remove `present?` ?

**Comment by lowjoel** [comment]
I think that's minor, you can fix it with other changes next time. There are more important things at the moment.

**Pull request closed without merging**
