### PR TITLE
Hide save button for students and display save button for staff after submission

### LINKED ISSUE #1443: Cannot edit EXP for trainings
No `Save` button

### PR DESCRIPTION
**Pull request by allenwq**
This will fix #1443 as well

### CODE REVIEW

**Comment by fonglh** [comment]
In what situation should the exp for trainings be edited? Isn't it 0 or full exp?

**Comment by allenwq** [comment]
Mostly two cases:
1. Sometimes jobs fails, and the answer is not graded
2. Student missed the deadline because of coursemology problem, staff wants to further give them the bonus EXP.

**Comment by fonglh** [comment]
For case 1, can the job be resubmitted for grading instead of having the TA manually check and award?

**Comment by allenwq** [comment]
Can, then it becomes case 2.

**Pull request merged**
