### PR TITLE
Code sprint/achievement module controller

### PR DESCRIPTION
**Pull request by fonglh**
Depends on Coursemology/coursemology2#98

### CODE REVIEW

**Comment by lowjoel** [comment]
Rebase+squash noisy commits, then this looks good to merge. Well done :+1:

**Comment by wangqiang1208** [comment]
@fonglh Do you have time to rebase it ? Or I do for you in collab ?

**Comment by allenwq** [comment]
@lowjoel I think this is good to merge

**Comment by lowjoel** [comment]
@fonglh please rebase.

**Comment by allenwq** [comment]
@lowjoel I've rebased for Li Heng

**Pull request merged**
