### PR TITLE
Use released version of carrierwave

### PR DESCRIPTION
**Pull request by allenwq**
Replace #974

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq it doesn't pass.

**Comment by allenwq** [comment]
hmmm

in 0.11 stable the whitelist method is named `extension_white_list`, while in master is `extension_whitelist`...

Shall I change back to `extension_white_list` ?

**Comment by lowjoel** [comment]
=.= yeah, it's annoying but I guess we can't help it.

Why did we use the git version in the first place?

**Comment by weiqingtoh** [comment]
#145 From @allenwq: 
> The release version of Carrierwave haven't been updated for more than a year and it's not working well with RSpec3, there are some issues such as carrierwaveuploader/carrierwave#1421
So I'm using the one from their master branch.

**Comment by allenwq** [comment]
@lowjoel It passed !

**Comment by lowjoel** [comment]
Sigh, problems with using bleeding edge stuff :(

**Pull request merged**
