### PR TITLE
Update schema.rb to support rails 4.2

### PR DESCRIPTION
**Pull request by allenwq**
Just found that after the migration to Rails 4.2 #50, our schema file was broken. 

<code>rake db:schema:load</code> will give errors.

Run <code> db:schema:dump</code> in this PR.

Noticed that there are also syntax changed:

Before:
```
create_table "courses", force: true do |t|
  t.integer "instance_id", null: false
  t.index ["instance_id"], :name => "fk__courses_instance_id"
  t.foreign_key ["instance_id"], "instances", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_courses_instance_id"
end
```

Now:
```
create_table "instances", force: :cascade do |t|
  t.integer "instance_id", null: false, index: {name: "fk__courses_instance_id"}, foreign_key: {references: "instances", name: "fk_courses_instance_id", on_update: :no_action, on_delete: :no_action}
end
```

### CODE REVIEW

**Comment by lowjoel** [comment]
You're not supposed to migrate from scratch... you're supposed to db:schema:dump from a working application... migrations are meant for version-to-version changes.

**Comment by allenwq** [comment]
@lowjoel Know a new command, thanks !

In this case, <code>db:schema:dump</code> equals <code>db:migrate</code> plus manually reorder columns.

I've updated.

**Comment by lowjoel** [comment]
no, `rake db:schema:dump` is not a `db:migrate`. You are supposed to use a `rake db:schema:load` using the working Rails 4.1 database, upgrade Rails to 4.2, then `rake db:schema:dump`. `db:migrate` should not be used to recreate a database.

**Comment by lowjoel** [comment]
This trouble is only because in Rails 4.2 they added stuff to ActiveRecord... :(

**Comment by allenwq** [comment]
> You are supposed to use a rake db:schema:load using the working Rails 4.1 database, upgrade Rails to 4.2, then rake db:schema:dump. 

Yes, I'm doing the same thing now.

**Comment by lowjoel** [comment]
:+1:

**Comment by allenwq** [comment]
For this PR, I restored the rails 4.1 db first. Then <code>db:schema:load</code>.

But notice the issue in the schema_plus: https://github.com/SchemaPlus/schema_plus/issues/155, I still need to manually add the foreign key for polymorphic migrations.

**Comment by lowjoel** [comment]
After dumping does the foreign keys remain in the database?

**Comment by lowjoel** [comment]
I don't think that's the correct issue, it looks like a different problem.

**Comment by allenwq** [comment]
It is. I think those short handed syntax  in schema file are provided by schema_plus.

Now I've backed to rails 4.1 and setup the db, then go to 4.2 run <code>db:schema:dump</code>, the foreign key for readable_id is still missing.

**Comment by lowjoel** [comment]
That issue you linked to is complaining that schema_plus is creating relationships when they should not exist. The problem here is the reverse, that it is supposed to create relationships but it is not.

**Comment by allenwq** [comment]
@lowjoel  Are we talking about the same thing ?

The problem is, if you have polymorphic associations in the migration files, like:

```
  t.references :readable, polymorphic: true
```

and the schema file generated will be:

```
   t.integer  :readable_id
```

which is not work, errors:

```
   PG::UndefinedTable: ERROR:  relation "readables" does not exist
```

But it works in previous version of schema_plus. Now we need to manually add a <code>foreign_key:false</code> to let it work:
```
   t.integer  :readable_id, foreign_key: false
```

So that's why the issue says it has problems with polymorphic models

**Comment by lowjoel** [comment]
Then why do you have a commit that says "add missing foreign key references?"

**Comment by allenwq** [comment]
Sorry, maybe my message confused you. 

But you can check the changes in that commits, It adds a <code>foreign_key:false</code> to the readable column.

**Comment by lowjoel** [comment]
:flushed:

**Comment by allenwq** [comment]
:+1:  Thanks ! this PR was urgent cause all other PRs need it ><

**Pull request merged**
