### PR TITLE
Enable rich text editing for video comments

### PR DESCRIPTION
**Pull request by weiqingtoh**
@yichenshen any comments?

### CODE REVIEW

**Comment by yichenshen** [comment]
Looks good! There should be any need to migrate all the old comments right?

**Comment by weiqingtoh** [comment]
The old comments I made appear as plain text, I think it should be fine!

**Comment by yichenshen** [comment]
I see, yup, then shouldn't have anything else already.

**Comment by kxmbrian** [comment]
Could you remove `client/yarn-error.log` from the commit?

**Pull request merged**
