### PR TITLE
Override send_devise_notification.

### PR DESCRIPTION
**Pull request by fonglh**
This makes it use the existing queue setup for ActiveJob to deliver
ActionMailer messages in the background.

### CODE REVIEW

**Comment by fonglh** [comment]
How to write a spec for this?

**Comment by allenwq** [comment]
@fonglh Create a user, and test that a email also enqueued in the queue ?

**Comment by fonglh** [comment]
@allenwq says that mails from the Email model aren't covered by this change, so confirmation emails can't be sent.

**Comment by allenwq** [comment]
@lowjoel Both `Email` and `User` need to override this method, we tried include the a concern for both models, but that do not work for email ( because the concern was included after `devise` ). 

I would prefer to monkey patch devise and override `send_devise_notification` in this case, what do you think ?

**Pull request closed without merging**
