### PR TITLE
Enable comments for questions in all assessment modes

### PR DESCRIPTION
**Pull request by allenwq**
1. Allow students to comment on guided assessment
2. Minor styling fix

### CODE REVIEW

**Comment by weiqingtoh** [comment]
LGTM :+1:

**Comment by weiqingtoh** [comment]
@allenwq need to fix the changes in locale key.

**Comment by allenwq** [comment]
@weiqingtoh Yah, Just realized, thanks !

**Comment by allenwq** [comment]
@weiqingtoh I have updated here.

**Pull request merged**
