### PR TITLE
Make course destroyable 

### LINKED ISSUE #932: Make course deletable
Currently course is not deletable due to lack of `dependent: :destroy` in some models in course.

This will help with the migration (we will be able to delete the course and migrate it again).

### PR DESCRIPTION
**Pull request by allenwq**
This will fix #932 

I have tested this by deleting a migrated course.

### CODE REVIEW

**Comment by lowjoel** [comment]
Specs?

**Comment by allenwq** [comment]
@lowjoel Create a course with everything associated and destroy it in specs ?

**Comment by lowjoel** [comment]
Just add the shoulda matchers, should be sufficient.

**Comment by lowjoel** [comment]
But, I think id you want to overkill, that's fine...

**Comment by allenwq** [comment]
OK, Will add shoulda matchers!

**Comment by allenwq** [comment]
Updated.

**Comment by lowjoel** [comment]
If we have problems with deleting courses again in future, then we probably should create a spec for it.

**Pull request merged**
