### PR TITLE
Don't prefer word array literal syntax

### PR DESCRIPTION
**Pull request by jsyeo**
Good to merge.

### CODE REVIEW

**Comment by jsyeo** [comment]
@lowjoel :point_up:

**Comment by lowjoel** [comment]
@jsyeo We still can't override stuff in the project config?

**Comment by jsyeo** [comment]
@lowjoel What do mean?

**Comment by lowjoel** [comment]
@jsyeo The unhound file resets Hound to Rubocop, then the real rubocop config will set our project settings.

**Comment by jsyeo** [comment]
@lowjoel oops. Kinda missed that.

**Comment by jsyeo** [comment]
Actually there's no need to set it to false. Hound prefers the non literal syntax https://github.com/thoughtbot/hound/blob/master/config/style_guides/ruby.yml#L484

**Comment by lowjoel** [comment]
But we're undoing ThoughtBot's config right...? The idea of unhound was to reset Hound's config to Rubocop, then we override that with our own config... not sure if I'm missing something

**Comment by lowjoel** [comment]
@jsyeo?

**Pull request merged**
