### PR TITLE
Fix for user pics on achievements page be round and no-stretch. Modif…

### PR DESCRIPTION
**Pull request by cysjonathan**
Fix for user pics on Achievements page be round and no-stretch.
selection_001

Modify style to reduce spacing between Date/time event in Latest Activity section. #1399
selection_002

### CODE REVIEW

**Comment by allenwq** [comment]
@cysjonathan I think we should have a general mixin for all the user images, all these should just include that mixin and specify width/height. What do you think ?

**Comment by cysjonathan** [comment]
Created and applied mixin as suggested.
One point is I'm not sure about Leaderboard page styling, there are stylings for a "groups" class (group-name, group-profile), with "course-leaderboard-groupuser-picture". I've not seen groups before and I'm not sure what functionality groups are for. Anyone familiar with the "groups" know **if group pictures have to be rounded too**?

**Comment by allenwq** [comment]
@cysjonathan Thanks ! In course settings you can enable group leaderboard, try that ?

**Comment by cysjonathan** [comment]
Made group leaderboard profile pictures rounded.

Also forces badges to be rounded. Should this be the expected behaviour? Or do we expect square/rectangle badges as well? (User page)
selection_005

(Achievement page)
selection_004

**Comment by allenwq** [comment]
Don't need to force the badge, there are some rectangle ones, the locked icon is an example: 
lock

**Comment by allenwq** [comment]
@cysjonathan Revert the badge, then this is mergeable.

**Pull request merged**
