### PR TITLE
[For Discussion] Controller Actions and Routes for Manual Award Achievements

### PR DESCRIPTION
**Pull request by weiqingtoh**
Just want to see some feedback on whether the controller convention, and routes I have defined are okay. 

For controller: Although this is `Course::UserAchievementsController`, I'm loading `@achievements`, hence have opted to do an update on `courseuser_ids` instead. 

For routes: Part of the intention was in line with exp transations - hence I'm suggesting for the routes to be the following: 

Verb | Controller Action | Route
--- | --- | ---
GET | index | `course/:id/admin/manual_award/achievements`
GET | edit | `course/:id/admin/manual_award/achievements/:id/edit`
PATCH/PUT | update | `course/:id/admin/manual_award/achievements/:id`

Ideally after that, we can part `experience_points` under the `manual_award` namespace.

---

My plan is to PR a skeleton controller and routes first, and add in the views later on.

### CODE REVIEW

**Comment by lowjoel** [comment]
Not sure I understand you -- I don't see where you're loading `@achievements`?

What would the user see in the index and edit actions? What would be done in the update action?

**Comment by weiqingtoh** [comment]
This line loads @achievements & @achievement -> 
```ruby
load_and_authorize_resource :achievement, through: :course, parent: false, class: Course::Achievement.name
```

Current intention is to show all achievements in `index` page, click on a particular achievement to go to `edit` page.

In the `edit` page, there will be a form to display all students for that particular achievement `collection_check_box`, and the admin can select who to award / take away achievements from. The submit button will make a `PATCH/PUT` to the `update` action.

**Comment by lowjoel** [comment]
Wouldn't this duplicate the functionality of Course::AchievementsController?

**Comment by weiqingtoh** [comment]
If that's the case does it make sense to add the methods to the AchievementsController instead?

**Comment by lowjoel** [comment]
Personally I felt that the separation between admin and student views to be rather incongruous, what does the rest think? @allenwq @kxmbrian @fonglh you guys have used Coursemology before.

**Comment by weiqingtoh** [comment]
I used this as it is similar to V1 design, but V1 had an auto-assign boolean flag to determine if it was manual or auto award. Now since we have the conditions solver, I think there is no need for that flag. 

Another idea is to have the `show` method under AchievementController, to display a particular achievement and all `CourseUsers` who have obtained it. Then authorised users will be able to access a page for award/take away achievements to edit `course_user_achievements`.

**Comment by lowjoel** [comment]
Would there be a situation where an instructor would want to grant/take away more than achievement at a time?

**Comment by weiqingtoh** [comment]
I suspect the UI to do that will be a little too tough. In those cases I propose the instructor to update it one achievement at a time. 

Unless you are say that I want to strip all (or some) achievements off a certain student, then ... that _might_ happen.

**Comment by lowjoel** [comment]
So then there's the course user page, which does allow multiple achievements to be added/removed, and the achievements page, which allow multiple students to get that or remove that achievement. I think that's sufficient?

**Comment by luoyanjie** [comment]
Removing multiple achievements, sound like a case of error lor. Also can be a case of punishing a student.

**Comment by lowjoel** [comment]
I don't suppose there will be a scenario where a person will remove multiple achievements from multiple students -- that sounds terrible.

**Comment by luoyanjie** [comment]
Errors I guess. E.g.: Oh shucks, allocate wrongly.

regards


LUO Yanjie (Mr)
User Engagement Designer,
Experimental Systems and Technology Lab (ESTL)
Tel: +65 9382 9403 
==============================
“Sounds like you will need about 15 years in MOE, Ben" 
                            - Mr Chia Hai Siang

**Comment by fonglh** [comment]
The admin and student views in v1 are pretty similar, except for some confusing repurposing of the links. Is that the incongruity you're referring to?

**Comment by lowjoel** [comment]
I think there's a duplication of functionality -- the achievements in the main app menu does similar things to what the achievements in the admin app menu does

**Comment by allenwq** [comment]
As long as we are consistent, I think some of the admin components can be merged with the non-admin ones if they have duplications in the implementation and functionalities( like in this case ).

**Comment by lowjoel** [comment]
@weiqingtoh enough information to move on?

**Comment by weiqingtoh** [comment]
More or less, the last issue that I need to resolve is which controller to place the methods for manual award. Was discussing with @allenwq on whether to put it into a `Course::Achievement` namespace with `Course::Achievement::UserController` and `Course::Achievement::AchievementController`, or just retain the current suggestion. Any thoughts?

**Comment by lowjoel** [comment]
If you are implementing the achievement page, then ticking the students to award, it should be in the achievement controller

**Comment by weiqingtoh** [comment]
Replaced by #898

**Pull request closed without merging**
