### PR TITLE
Build deppbot bundle update branches too.

### PR DESCRIPTION
**Pull request by fonglh**
Need to know if gem updates break anything.

### CODE REVIEW

**Comment by allenwq** [comment]
Why we need this ?  deppbot will always PR and build.

**Comment by fonglh** [comment]
Yes, but the travis file suggests that it was configured not to. This makes it explicit that we want the build.

**Comment by allenwq** [comment]
Now This meawns it will build on push the branch + open PR right ? so it will build 2 times when open the PR ?

**Comment by fonglh** [comment]
ohh ok I misunderstood what this was doing.

**Pull request closed without merging**
