### PR TITLE
Bundle Update on 2017-04-19

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [activerecord-import](http://github.com/zdennis/activerecord-import), [0.17.2...0.18.1](https://github.com/zdennis/activerecord-import/compare/v0.17.2...v0.18.1)
- Updated: [globalid](https://github.com/rails/globalid), [0.3.7...0.4.0](https://github.com/rails/globalid/compare/v0.3.7...v0.4.0) ([CHANGELOG](https://github.com/rails/globalid/blob/master/CHANGELOG.md))
- Updated: [json](http://github.com/flori/json), [2.0.4...2.1.0](https://github.com/flori/json/compare/v2.0.4...v2.1.0) ([CHANGELOG](https://github.com/flori/json/blob/master/CHANGES))
- Updated: [validates_hostname](https://github.com/KimNorgaard/validates_hostname), [1.0.6...1.0.7](https://github.com/KimNorgaard/validates_hostname/compare/v1.0.6...v1.0.7) ([CHANGELOG](https://github.com/KimNorgaard/validates_hostname/blob/master/CHANGELOG.rdoc))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
111 Pull Requests sent and 11 hours, 12 minutes, and 37 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by allenwq** [comment]
@weiqingtoh Any comments to activerecord-import ? seems they changed a lot.

**Comment by weiqingtoh** [comment]
@allenwq actually we should remove that gem cause then migration has been done already. Any ideas how we can deal with this? Maybe comment the migration out and add a version?

**Comment by allenwq** [comment]
ehh, which migration you were referring to ?  I thought the gem was used to dealing with bulk insert TODOs ?

**Comment by weiqingtoh** [comment]
Oh I forgot I used it for bulk inserting TODOs >_< 

Anyway, the changes are not breaking changes. The one that affects us is that uniqueness validations are not run when we do bulk imports. This does not affect us as have [declared to disable validations on bulk import](https://github.com/Coursemology/coursemology2/blob/master/app/models/course/lesson_plan/todo.rb#L45). Currently we can leave it as it is as I prefer it to be more explicit. However, if in the future we wish to run more non-uniqueness validations, then maybe removing `validate: false` would be more appropriate. 

Also, there is a spec which guards against this, so it seems to be working. 

If that's the case, I'll just merge this first @allenwq.

**Comment by allenwq** [comment]
👍

**Pull request merged**
