### PR TITLE
Time bounded helpers

### PR DESCRIPTION
**Pull request by allenwq**
For #134

### CODE REVIEW

**Comment by lowjoel** [comment]
I think we need better names.

How about:
 - time_period_class for 'expired' 'active' 'not_yet_valid'
 - valid_in_future? will be expired? active? not_yet_valid?

for symmetry?

**Comment by allenwq** [comment]
>< Naming is hard.

But have 3 different time_period classes is a good idea, will update

**Comment by lowjoel** [comment]
expiry_status? idk

**Comment by allenwq** [comment]
Updated, now we've 3 time period helpers.
Changed <code>future_class</code> to  <code>time_period_class</code>, means that it's not only for <code>future</code> class

**Comment by lowjoel** [comment]
remove the diagrams please =.= the generated docs won't be monospace...

**Comment by allenwq** [comment]
:-P diagrams are just for fun, will remove before merge, does other parts
need change ?

**Comment by lowjoel** [comment]
everything else is fine. nice work.

**Comment by allenwq** [comment]
Diagrams removed :(

**Pull request merged**
