### PR TITLE
Upgrade to MUI v5 - rebased from client-deps-2 upgrade

### PR DESCRIPTION
**Pull request by ekowidianto**
Rebased upgrade based on #4363 

Tests failed here since @material-ui/pickers require MUI v4. Refer to unrebased branch (above) for all passed test cases.

Related to #4363

### CODE REVIEW

**Review by zhuhanming — APPROVED** [review]
I've been testing out the app over the past week - super solid work! I don't think there are any major issues. Code-wise, I've roughly looked through and it looks ok.

I'll list out issues that I've found / will find in a separate comment. @cysjonathan @lyskevin would appreciate your help in testing as well!

**Comment by zhuhanming** [comment]
- [ ] Button positioning and margin bottom seems to have changed for forum post response

   Screenshot 2022-03-25 at 9 53 02 AM

   Screenshot 2022-03-25 at 9 53 15 AM

- [ ] Rebase

(will edit this comment as I go)

**Review by zhuhanming — APPROVED** [review]
I think this looks good to go to me.

I've added more items to the list above, but they're minor nits - we should be able to deploy this.

**Comment by ekowidianto** [comment]
> * [ ]  Loading spinners on some screens lack padding on top. I think lesson plan screen has the same issues.

This should have been fixed in this commit https://github.com/Coursemology/coursemology2/pull/4391/commits/bd52e915be4bc0b77320e6960f286e74472a590b

**Comment by ekowidianto** [comment]
> * [ ]  MUI datepicker - if you manually type in a date, then click the picker and click out, the date that was typed in gets resetted to the date before the manual typing (if there's no previous date, the field gets cleared).

Seems like it's MUI's problem. See: https://github.com/mui/material-ui/issues/31919

**Comment by zhuhanming** [comment]
Ok then let us merge this.

**Comment by ekowidianto** [comment]
Closes #243

**Pull request merged**
