### PR TITLE
Test hound

### PR DESCRIPTION
**Pull request by jsyeo**

### CODE REVIEW

**Comment by jsyeo** [comment]
:confused:

**Comment by lowjoel** [comment]
looks like its ignoring our config.

**Comment by lowjoel** [comment]
I think once #120 is merged this can be closed.

**Comment by lowjoel** [comment]
why close? not fixed yet right

**Comment by jsyeo** [comment]
chill... i creating another PR to test the coveralls status api..

**Comment by lowjoel** [comment]
TEST ALL THE THINGS

**Pull request closed without merging**
