### PR TITLE
Check objects instead of classes against abilities

### PR DESCRIPTION
**Pull request by kxmbrian**
Fix for #813

### CODE REVIEW

**Comment by lowjoel** [comment]
I am okay with changing the classes to actual instantiated variables, but I do not want to instantiate an AR object just to check for permissions. AR objects can be expensive because of the callbacks.

Can we find another solution>

**Comment by lowjoel** [comment]
Maybe this can't be helped, the more I think of it.

**Comment by kxmbrian** [comment]
I can think of solutions if we want to add new abilities definitions and check against a user given some parameters instead of checking against the object/class that we are trying to access, but that'll probably break the semantics of cancancan. 

If we just use the existing abilities definitions, then I don't have a good workaround.

**Comment by lowjoel** [comment]
Okay, rebase against master. I'll merge this.

**Comment by kxmbrian** [comment]
@lowjoel ok, rebased.

**Pull request merged**
