### PR TITLE
Provide a setting to display output for public test cases

### PR DESCRIPTION
**Pull request by anirudhnigania**
Incorporated all the suggestions and fixes required. Created a new feature branch.

### CODE REVIEW

**Comment by weiqingtoh** [comment]
@allenwq LGTM. 

You guys might hate me for saying this but in the future we might need an individual assessment level setting on top of a course-level one.

@anirudhnigania once this is merged, can you create another issue to define an assessment settings adapter?

**Comment by allenwq** [comment]
> in the future we might need an individual assessment level setting on top of a course-level one.

@weiqingtoh Yes, that's the plan 😄 . That's why there's a TODO in the code.

@anirudhnigania I agreed you to put this in the course level is because I realised it might not be easy for you to add a new settings adapter and refactor the exiting views, but please submit an issue too as @weiqingtoh suggested.

**Comment by anirudhnigania** [comment]
@weiqingtoh @allenwq Yeah Sure, will submit an issue for an assessment settings adapter.

**Comment by anirudhnigania** [comment]
I have created an issue for assessment settings adapter as suggested by @weiqingtoh

**Pull request merged**
