### PR TITLE
style(finalise-button): shift finalise button to the right

### LINKED ISSUE #4339: Improve UX to prevent unintentional submissions
Currently, it seems like to new users of Coursemology, it is very easy to unintentionally submit their work even when it's incomplete. This has happened over the past two cohorts of CS2040S students, which suggests that there may be some glaring UI/UX issues.

One suggestion by student Huzaifa Raghav on the CS2040S forums is as such (which has been upvoted by quite a number of students):

> I think part of the problem is that the 'Save Draft' and Finalise buttons are too close together. The screenshot below is how it looks on a laptop (browser window taking up the full screen).
>
> Screenshot+2022-01-13+at+10 26 41+PM
>
> If some styling was added to push the button to the right a bit more or even all the way (like below) it might help a bit.
>
> Screenshot+2022-01-13+at+10 27 14+PM

Another suggestion by student Richard Dominick is:

> An alternative could be to only show the "Finalise Submission" button at the very last question of each problem set; this will not affect those who wants to submit blank answers, and for those who wants to attempt every question, they will definitely encounter the last question before submitting?

I think both are pretty solid suggestions, and should be looked into.

### PR DESCRIPTION
**Pull request by syoopie**
Resolves #4339

### CODE REVIEW

**Comment by syoopie** [comment]
image

**Comment by ekowidianto** [comment]
@syoopie Can you fix the lint? Thanks

**Comment by ekowidianto** [comment]
There is another finalise submission button submissioneditstepform (for autograded assessment). Could you move the position for that button as well?

**Review by ekowidianto — APPROVED** [review]
LGTM! Please squash it into 1 commit.

**Pull request merged**
