### PR TITLE
Add explanations to the python online editor

### PR DESCRIPTION
**Pull request by justwudi**
Use the same explanations as v1 for the prepend and append code blocks as well as the test cases.

### CODE REVIEW

**Comment by allenwq** [comment]
@justwudi Can we also explain "submission template" and "solution template" ? 
I think solution template is also optional ? is it only needed when the template has a syntax error or infinite loop ?

**Comment by allenwq** [comment]
@fonglh When is the solution template used ?  how shall we explain that to users ?

**Comment by fonglh** [comment]
It's actually not used anywhere. It provides a 'bypass' if a syntax incorrect template needs to be shown to the student.

If present, solution template is used for producing the test cases, instead of the submission template.

Ok, that was the technically correct explanation.

The much simpler one would be that it is a place for them to store their solutions for future reference, and a correct one is needed if the template for students cannot be run (syntax errors, infinite loops or other errors).

**Comment by allenwq** [comment]
@fonglh  If solution template is empty but the submission template has an infinite loop, will it use the solution template and pass the import ?

**Comment by fonglh** [comment]
Yes, but the file must be there. I'm not sure if the online editor puts an empty file there, or no file at all, if the solution template box is left empty.

**Comment by justwudi** [comment]
The online editor will leave an empty file there if the solution is left empty.

**Comment by allenwq** [comment]
@fonglh  so when there's an syntax error or infinite loop, the template file is actually not required to be filled in ?  Think in that case we can document the template file as " it is a place for them to store their solutions for future reference" ?

**Comment by fonglh** [comment]
Yes that's fine

**Comment by allenwq** [comment]
@justwudi any updates ? think we just do that ?

**Pull request merged**
