### PR TITLE
Modify activity framework

### PR DESCRIPTION
**Pull request by xzhflying**
depends on #440
* Add `course` column in `activity` schema
* Remove `course` column from `course_notifications` schema
* Modify some related APIs

### CODE REVIEW

**Comment by lowjoel** [comment]
I don't agree with this design. Why should every activity be necessarily associated with a course?

**Comment by xzhflying** [comment]
I want to solve this problem: when load unread popups of current course from user_notifications, I need to know which course does one notification belong to. I can also add `course` in `user_notifications` but will that be many duplications? And also I think most activities are about one course.

**Comment by lowjoel** [comment]
I'm not sold. Why does it matter that the user only gets notifications from the current course?

 - If you are only in one course, if you are anywhere in Coursemology, you won't care.
 - If you are in more than one course, the notifications provide context by its description and clicking on it should bring you to the correct course page.

You're introducing an unnecessary dependency cycle here.

**Comment by allenwq** [comment]
As discussed today in the meeting:

1. Loading popup notifications before every action would interrupt current workflow (e.g. If I'm doing trainings, I should not see popups from missions)

2. To resolve this issue we will show popups as a ballon in the right corner, and it pops up when user clicks

3. This also allows user to receive popups from another course(since the current workflow won't be interrupted), then there is no need to make activities belongs to a course.

So I'll close this PR

**Pull request closed without merging**
