### PR TITLE
Remove Coursemology Team signoff from emails.

### PR DESCRIPTION
**Pull request by fonglh**
Emails should be sent on behalf of the course and not the dev team.

### CODE REVIEW

**Comment by weiqingtoh** [comment]
Can we return the signoff for global/system announcements?

**Comment by fonglh** [comment]
Ok, I'll make the no signoff layout the default, then create another one for the global/system announcements.

**Comment by fonglh** [comment]
Can't find any code that sends emails for global/system announcements, and creating those locally didn't result in any emails being sent too.

**Comment by weiqingtoh** [comment]
Ok, I merge this first, but can we create an issue to do emails for global/system announcements? Thanks!

**Pull request merged**
