### PR TITLE
style(announcements): change new announcement icon

### PR DESCRIPTION
**Pull request by syoopie**
New Icon:

image

### CODE REVIEW

**Comment by cysjonathan** [comment]
Why not just a + icon?
image

**Comment by syoopie** [comment]
Announcement is kind of like creating a post so i though something similar to the previous icon, with the addition of a plus sign will be more appropriate

**Comment by cysjonathan** [comment]
I am thinking across components, we can have a common "create"/"new" icon for announcements, videos, assessments, lesson plan events, achievements, surveys, etc.

**Comment by ekowidianto** [comment]
@syoopie Can use AddBoxOutlined and change the sx color to white? I think you can abstract this component as a common library component and reuse the component for new achievement as well.

Thanks

**Comment by qreoct** [comment]
Should I standardize and also use `AddBoxOutlined` for the admin panel? (New Instance & New Announcement). Right now in most pages the 'add' button is a text button.

image

**Comment by ekowidianto** [comment]
@qreoct yup!

**Review by ekowidianto — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
