### PR TITLE
 Allow achievements to have requirements

### PR DESCRIPTION
**Pull request by lowjoel**
Replaces #100.

Still not working, though.

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq the build is failing, can you run this locally and see if it fails on your computer? It runs fine on my own computer.

**Comment by allenwq** [comment]
@lowjoel Same exception as travis, I cannot run <code>db:setup</code>

**Comment by lowjoel** [comment]
travis isn't failing at db:setup, it's failing at loading the factories.

**Comment by allenwq** [comment]
Seems to be setup
```
$ rake db:setup
rake aborted!
NoMethodError: undefined method `stringify_keys' for #<#<Class:0x007f91f2b06040>:0x007f91f145c8d0>

```

**Comment by lowjoel** [comment]
okay, going blind =.= not sure why it's broken though...

**Comment by lowjoel** [comment]
Found the bug, going to fix in the gem.

**Comment by allenwq** [comment]
:+1:

**Comment by lowjoel** [comment]
Waiting for schemaplus/schema_plus_core#2

**Comment by lowjoel** [comment]
This should work now. Review and merge when it all passes.

**Pull request merged**
