### PR TITLE
Try to reduce the random failure in specs

### PR DESCRIPTION
**Pull request by allenwq**
See #1426 and #1427 

Randomized hostname leads to lots of random failure in travis. 

1. Use default instance with a fixed hostname for most of the specs, this will hopefully reduce the random test failure rate a lot.
2. Limit the users in admin users spec, the failure before is because the users are created in other places while running the specs.

Test performance should also be improved since fewer records are created.

### CODE REVIEW

**Comment by fonglh** [comment]
Is there anywhere we do need 2 instances?

**Comment by allenwq** [comment]
@fonglh You search `create(:instance)` in the code base, still many places we need it, like for instance related tests.

**Comment by fonglh** [comment]
Ok, so many places were changed I thought it was a global search and replace, haha

**Comment by allenwq** [comment]
A lot of failures if you just global replace :-)

**Pull request merged**
