### PR TITLE
Standardise private controller methods - params first

### PR DESCRIPTION
**Pull request by weiqingtoh**
Arising from a discussion in #765, this PR:
 - Updates `CONTRIBUTING.md`, and
 - Standardises params to be the first private method for controllers.

### CODE REVIEW

**Comment by lowjoel** [comment]
Maybe we can also infer from the normalisation that you just did, that it's:

 1. params
 2. before_action/after_action callbacks (since those are at the top of the controller)
 3. then finally helper methods

does that seem right?

**Comment by weiqingtoh** [comment]
I see another kind of method, authorisation ones. Any preference on where those should go? 

Once we set, I'll do another check and adjust.

**Comment by lowjoel** [comment]
Authorisation methods are called using before_action right?

**Comment by lowjoel** [comment]
@weiqingtoh .DS_Store got committed.

**Comment by weiqingtoh** [comment]
Okay this should be fixed now.

**Pull request merged**
