### PR TITLE
Speed up test

### PR DESCRIPTION
**Pull request by allenwq**
The total time was reduced by 40% in my local

### CODE REVIEW

**Comment by jsyeo** [comment]
Woot!

**Comment by lowjoel** [comment]
I don't agree with stubbing a class globally.

**Comment by allenwq** [comment]
I don't think It's global? Stub has an per example life cycle, each example
can be run in isolation.

**Comment by lowjoel** [comment]
But you're stubbing the entire class. So on another thread you will end up with the stub also.

**Comment by allenwq** [comment]
Kaminari stores such info in a class variable and a global config
varribale, Do you think there are other ways to stub it ?

Also are we going towards concurrent tests in future? Why not adopt it now
and see how it goes ?  :-)

**Comment by lowjoel** [comment]
One way is to specify the number of items as a query string parameter.

If you want to run the tests in parallel, go ahead and file a PR. The existing parallel tests gem seems like a bad idea to me, however.

**Comment by allenwq** [comment]
>One way is to specify the number of items as a query string parameter.
I don't get your point here

I did some research before, haven't found any pretty way to do concurrent testing now.

https://github.com/rspec/rspec-core/issues/1254
And look at this issue, Rspec is going to support multi-threading, I would expect the Rspec library to use locks to handle stubs other than preventing user to stub the global object.

**Comment by lowjoel** [comment]
So, you can tell Kaminari how many items you want on that page using a query string parameter, e.g. /courses?count=10 that would show 10 entries.

Of course, all pages using Kaminari would need to have this enabled.

**Comment by allenwq** [comment]
I think Kaminari does not support this ?  However, even it's supported, I don't think it's correct, because it's another feature not the pagination itself. 

Is it possible to use stub for now and we come back to address this issue when concurrent testing comes ?  Because this boosts the development progress at some level.

**Comment by lowjoel** [comment]
It definitely must support this. It's unreasonable to not allow anyone not to specify the number of records per page.

To your second point, no. I favour correctness over performance.

**Comment by allenwq** [comment]
There is no reason for them to do any interacting with end point user.

Normally it's travis takes too long time, but I understand you, so OCD :-)

**Comment by lowjoel** [comment]
There is. Every time there's an option for pagination, there will be a way to specify how many records per page, see Google -- you can specify you want 10, 25, 50, 100 results per page. It's not Kaminari which will magically handle it. Controllers need to be aware and set Kaminari appropriately.

**Comment by allenwq** [comment]
Of course we can let our controllers to support this, but that is related to settings.

**Comment by allenwq** [comment]
So that I'll close this PR since it's not doing correct thing, thanks for the comments !

**Comment by lowjoel** [comment]
You can actually still get the first commit merged though, the one where you specify `creator:` and `updater:`

**Comment by allenwq** [comment]
OK, I'll use another PR

**Pull request closed without merging**
