### PR TITLE
Bundle Update on 2016-04-09

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [capybara](http://github.com/jnicklas/capybara), [2.6.2...2.7.0](https://github.com/jnicklas/capybara/compare/2.6.2...2.7.0) ([CHANGELOG](https://github.com/jnicklas/capybara/blob/master/History.md))
- Updated: [factory_girl](https://github.com/thoughtbot/factory_girl), [4.5.0...4.7.0](https://github.com/thoughtbot/factory_girl/compare/v4.5.0...v4.7.0) ([CHANGELOG](https://github.com/thoughtbot/factory_girl/blob/master/NEWS))
- Updated: [factory_girl_rails](http://github.com/thoughtbot/factory_girl_rails), [4.6.0...4.7.0](https://github.com/thoughtbot/factory_girl_rails/compare/v4.6.0...v4.7.0) ([CHANGELOG](https://github.com/thoughtbot/factory_girl_rails/blob/master/NEWS))
- Updated: [puma](https://github.com/puma/puma), [3.3.0...3.4.0](https://github.com/puma/puma/compare/v3.3.0...v3.4.0) ([CHANGELOG](https://github.com/puma/puma/blob/master/History.txt))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
45 Pull Requests sent and 4 hours, and 47 minutes saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by lowjoel** [comment]
These look like Capybara problems...

**Comment by lowjoel** [comment]
Gunna push changes, see how many more fail. Don't merge yet.

**Comment by lowjoel** [comment]
@allenwq the guided spec failure is because the spec is wrong, can you commit a fix to this branch?

**Comment by allenwq** [comment]
@lowjoel Fixed the guided spec, any comments ?

**Comment by lowjoel** [comment]
OK, squash your commit with my broken specs commit, and squash both commits into the Deppbot commit.

So the Deppbot commit passes CI. I'll merge this when that's done.

**Comment by allenwq** [comment]
I see, done !

**Comment by lowjoel** [comment]
@allenwq awesome!

**Pull request merged**
