### PR TITLE
Allow administrators that are not enrolled in a course to attempt submissions

### PR DESCRIPTION
**Pull request by weiqingtoh**

### CODE REVIEW

**Comment by fonglh** [comment]
This means that administrators will gradually show up on more and more courses as phantom managers?

**Comment by weiqingtoh** [comment]
Yup, unfortunately so. Not sure if there are other ways? I don't think we want to allow submissions to exist without a course_user. That would mean bending `experience_points_record` to fit our use case.

**Comment by fonglh** [comment]
I think it would help to differentiate between phantom course_users created with this "admin override", verses phantom course_users created by joining a course. That'll allow us to tweak the displays to hide them properly.

Another problem with not differentiating is that the course dropdown menu for admins will get longer and longer. It'll be confusing for them to see that they're showing up in courses they never enrolled in.

**Comment by fonglh** [comment]
Maybe add an `observer` role to CourseUser which doesn't show up anywhere on the frontend and still retains the 'Enrol' button.

Enrolment will then update the administrator's CourseUser role to one of the normal ones.

**Comment by weiqingtoh** [comment]
Phantom is in essence an observer role already, so what you are suggesting should also be applied to all phantom course users. I think there is no need for an re-enrolment, that confuses users into thinking whether their current data might get wiped if they re-enrol. 

Anyway this happens only for the administrators and they should be able to delete their ownselves if need be?

**Comment by kxmbrian** [comment]
We have the same issue for surveys, albeit less critical - admins can create and edit surveys, but cannot do a 'dry run' of the student's view unless they are CourseUsers. Should we make the solution more general such that CourseUsers are automatically created for admins anywhere a CourseUser is required to achieve full functionality (i.e. full super-user-ness)?

Perhaps we can use `admin` instead of `observer` for the role naming since 'observer' connotes intentional observing similar to phantoms as @weiqingtoh pointed out. `observer` suggests that the CourseUser will be hanging around for a bit, instead of going in just to administer some fix or check on a problem.

I agree with @fonglh that the expanding course list and admins being added to the class roster will be an issue, though as @weiqingtoh highlighted, this only happens for admins and *most* of us admins can bear deleting manually if need be.

**Comment by benleong** [comment]
Are we confusing instructor and admin? Instructors can create and should be
able to test surveys.

Instance admins are super-users for an instance and should be able to do
everything in an instance.

There's also the global admin. I hope we're not confused. Can we call the
global admin "root"?

**Comment by weiqingtoh** [comment]
> I think it would help to differentiate between phantom course_users created with this "admin override", verses phantom course_users created by joining a course. That'll allow us to tweak the displays to hide them properly.

@fonglh could you explain a little more on the need to differentiate between phantom course_users and admin override? 

If it's for displays to hide them, currently we only need to cater for phantom students. The only place where we need to handle phantom staff is at the public course page. I'm am ok for the 'observer' role only if we have a specific (and strong) use case for phantom course_staff vs 'observer' course_user (which can be a course_user or course_staff). I'm disagreeing now because it isn't very clear yet. Otherwise, the tradeoff of an additional mental load on the developers might not be worth it (to be fair, I've missed excluding phantom students quite a few times too, so this will definitely happen with observers).

> Should we make the solution more general such that CourseUsers are automatically created for admins anywhere a CourseUser is required to achieve full functionality (i.e. full super-user-ness)?

Any suggestions on how we can do this? My sense is that we should just implement this in the relevant models, ie. Submissions for assessment and surveys, so we have finer grained controls in each situation to create the course user. 

> We have the same issue for surveys, albeit less critical - admins can create and edit surveys, but cannot do a 'dry run' of the student's view unless they are CourseUsers.
> Are we confusing instructor and admin? Instructors can create and should be able to test surveys.

@kxmbrian maybe clarify what you mean here? Can adopt the terminology below to be clearer.

> Instance admins are super-users for an instance and should be able to do everything in an instance.

Generally you are right - just to clarify, there are 3 levels of users, with the associated roles: 
 1. Global User - Normal, and Administrator. Administrators here are super-users, probably Coursemology core/dev team (+ a few others). 
 2. Instance User - Normal, Instructor and Administrator. Instructors can create course, Administrator here can do instance level role setting.
 3. Course User - Student, Teaching Assistant, Manager, Owner. Different roles to manage different parts of the course.

> There's also the global admin. I hope we're not confused. Can we call the global admin "root"?
I think we usually differentiate by using administrator vs instance admin, just to have parity with the codebase. We can rename to root but I think it's insignificant. 

---

Also, just to clarify, this PR is only for Global Administrators, not instance administrators.

**Comment by fonglh** [comment]
Instructors who keep close tabs on their participants would not want phantom managers enrolled in their courses, even if those phantom managers are administrators.

Administrators would also not expect to be enrolled in courses, even as phantom, simply by attempting an assessment. Being enrolled affects which courses are displayed to them.

That's why I think it's necessary to differentiate between phantom and admin override.

Anyway, @allenwq is considering the approach of just doing away with the CourseUser requirement and doing nil checks on the experience points record.

**Comment by benleong** [comment]
Frankly, it sounds to me that you guys are screwing up the design of the
access control.

There are actually 2 concepts: (i) permissions and (ii) roles.

A permission is the ability to do something, whatever. Roles is a
collection of permissions. And we can assign roles to users.

If the design of the access control is proper, you shouldn't be having this
discussion. Maybe we should all have a meeting to discuss?

**Comment by kxmbrian** [comment]
> Any suggestions on how we can do this? My sense is that we should just implement this in the relevant models, ie. Submissions for assessment and surveys, so we have finer grained controls in each situation to create the course user.

One naive way is to create a CourseUser on the fly  when `#current_course_user` is called when (1) there is none found and, (2) the user is a global admin.

> @kxmbrian maybe clarify what you mean here? Can adopt the terminology below to be clearer.

- Current situation for surveys: 
    - Course staff (i.e. instructors) can create and test surveys regardless of their role as a global or instance user.
    - Both global and instance admins who are not enrolled as a staff cannot test a survey. They can only create surveys.
- This is basically the same problem as the one addressed by your PR - global and instance admins cannot "dry run" an item because CourseUser is missing, so I'm asking whether it makes sense to do a more general solution.

**Comment by benleong** [comment]
Maybe we should have a meeting to discuss this issue as well. Frankly,
there many funny architectural decisions that you guys made that have made
it v awkward to do a lot of things.

Let's have a meeting next Tues to discuss?

**Comment by fonglh** [comment]
As discussed in the meeting, we have decided to remove the CourseUser not null requirement from the experience_points_records table.

Couple of things to note:

1. Add `nil` checks where necessary as some parts of the code might assume the presence of a CourseUser.
2. Add logic to populate the course_user_id column if the administrator actually enrolls in the course.

**Pull request closed without merging**
