### PR TITLE
Change cancancan fork used

### LINKED ISSUE #706: cancancan does not correctly use table aliases in the WHERE clause
When we define the following rule
```
read_hash = { course_user: { course: { course_users: { user_id: user.id, workflow_state: 'approved', role: [1,2,3] } } } }
can :read, Course::ExperiencePointsRecord, read_hash
```
Calling `accessible_by` generates the query:

```sql
...
FROM
	"course_experience_points_records" 
		LEFT OUTER JOIN "course_users"
			ON "course_users" . "id" = "course_experience_points_records" . "course_user_id" 
		LEFT OUTER JOIN "courses"
			ON "courses" . "id" = "course_users" . "course_id"
				AND "courses" . "instance_id" = $1 
		LEFT OUTER JOIN "course_users" "course_users_courses"
			ON "course_users_courses" . "course_id" = "courses" . "id"
WHERE
	"course_experience_points_records" . "course_user_id" = $2
	AND (
		"course_users" . "user_id" = $3
		AND "course_users" . "workflow_state" = $4
		AND "course_users" . "role" IN (1, 2, 3)
	)  [["instance_id", 1], ["course_user_id", 4], ["user_id", 9], ["workflow_state", "approved"]]
```
which is incorrect.  `course_users` should be generated as `course_users_courses` in the WHERE clause:
```sql
WHERE
	"course_experience_points_records" . "course_user_id" = $2
	AND (
		"course_users_courses" . "user_id" = $3
		AND "course_users_courses" . "workflow_state" = $4
		AND "course_users_courses" . "role" IN (1, 2, 3)
	)  [["instance_id", 1], ["course_user_id", 4], ["user_id", 9], ["workflow_state", "approved"]]
```

### PR DESCRIPTION
**Pull request by kxmbrian**
Don't merge yet. We still need to remedy a couple of broken tests.

Fixes #706.

### CODE REVIEW

**Comment by lowjoel** [comment]
Please investigate every failing test case. I’m not entirely convinced that the solution I implemented works in all cases. Identify them and let me know, I’ll see what else needs to be fixed in the fork.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by kxmbrian** [comment]
The only cases failing now are for the lesson plan event abilities. `accessible_by` works properly when called on a class
```ruby
Course::LessonPlan::Event.accessible_by(subject)
```
but fails in the case of
```ruby
course.lesson_plan_events.accessible_by(subject)
```

**Comment by lowjoel** [comment]
What do you mean by "fails"?

**Comment by kxmbrian** [comment]
We get 
```
ActiveRecord::StatementInvalid:
       PG::UndefinedColumn: ERROR:  column course_lesson_plan_items.user_id does not exist
```
because
```
course.lesson_plan_events.accessible_by(subject)
```
generates something like
```sql
SELECT 
  ...
FROM "course_lesson_plan_events" 
  LEFT OUTER JOIN "course_lesson_plan_items" "lesson_plan_items_course_lesson_plan_events" 
    ON "lesson_plan_items_course_lesson_plan_events"."actable_id" = "course_lesson_plan_events"."id" 
    AND "lesson_plan_items_course_lesson_plan_events"."actable_type" = $1 
  LEFT OUTER JOIN "courses" 
    ON "courses"."id" = "lesson_plan_items_course_lesson_plan_events"."course_id" 
    AND "courses"."instance_id" = $2 
  LEFT OUTER JOIN "course_users" 
    ON "course_users"."course_id" = "courses"."id" 
  INNER JOIN "course_lesson_plan_items" 
    ON "course_lesson_plan_events"."id" = "course_lesson_plan_items"."actable_id" 
WHERE "course_lesson_plan_items"."course_id" = $3 
  AND "course_lesson_plan_items"."actable_type" = $4 
  AND (("course_lesson_plan_items"."user_id" = 2051 
         AND "course_lesson_plan_items"."workflow_state" = 'approved' 
         AND "course_lesson_plan_items"."role" IN (1, 2, 3)) 
       OR ("course_lesson_plan_items"."user_id" = 2051 
         AND "course_lesson_plan_items"."workflow_state" = 'approved'))
```

For the last 5 lines, `course_lesson_plan_items` should be `course_user`. Also, the `course_lesson_plan_items` table need not be joined twice.

**Comment by kxmbrian** [comment]
Using https://github.com/kxmbrian/cancancan/tree/fix-issue-284 allows the test to pass

**Pull request merged**
