### PR TITLE
`bundle update`

### PR DESCRIPTION
**Pull request by lowjoel**

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq is the coverage down because Carrierwave changed something?

**Comment by allenwq** [comment]
Yes, should because of https://github.com/carrierwaveuploader/carrierwave/commit/6bbaa6cfa871d875d069c4217db8b92b85e676c8

**Comment by lowjoel** [comment]
So that line should be renamed to use `extension_whitelist` instead of `extension_white_list`?

**Comment by allenwq** [comment]
Yah, think so.  Or use the new `content_type_whitelist`

**Comment by allenwq** [comment]
You wanna fix it or I do in a separate PR?

**Comment by lowjoel** [comment]
Is there documentation on that feature?

It's a bit annoying that after so long they have not released a new version of CarrierWave...

**Comment by lowjoel** [comment]
You can commit to my branch here to fix it, I guess.

**Comment by allenwq** [comment]
I noticed that they have updated their README..

It's even annoying that they don't have a changelog, they just rename the method and silently update the README.

**Comment by allenwq** [comment]
Oh, wait they have a history

**Comment by lowjoel** [comment]
Thanks!

**Pull request merged**
