### PR TITLE
Tweak spacing between announcement title and timestamp to be more con…

### PR DESCRIPTION
**Pull request by caramelcat**
…sistent with the activity feed

announcement_date_look_like_activity_feed

### CODE REVIEW

**Comment by weiqingtoh** [comment]
Random qn - can we check if the styling looks okay on mobile? Not sure if we should go for absolute pixels or %.

**Comment by caramelcat** [comment]
@weiqingtoh I think it looks ok? Anyway Bootstrap's font sizes are already in px, so the whole point is moot?


announcements_tweak_mobile

**Comment by weiqingtoh** [comment]
That's true. Then this is okay 👍

**Comment by benleong** [comment]
Looks good. Thanks!

**Pull request merged**
