### PR TITLE
Implement adding comments to answers

### PR DESCRIPTION
**Pull request by lowjoel**

### CODE REVIEW

**Comment by allenwq** [comment]
@lowjoel Shall we use the `Course::Discussion::PostsConcern` ? so that the subscription logic will also be handled.

**Comment by lowjoel** [comment]
That's for a standalone post controller. This is currently part of a submission so the concern isn't going to work.

**Comment by lowjoel** [comment]
The next PR which does annotations would need me to have a separate controller and I'll use it there.

**Comment by allenwq** [comment]
Then how will you handle the subscription for answers ?  So that students/TAs can receive emails when there is a new comment.

**Comment by lowjoel** [comment]
Probably deal with that later.

The concern does not help, because the submission is not a topic.

**Comment by allenwq** [comment]
@lowjoel Yah I see...

And I thought you namespace the submission controller was for adding an `Submission::Answer::Comments` controller and we will have the url in the form of `submissions/:id/answers:id/comments, any reason why not do that now ?

**Comment by lowjoel** [comment]
THat one is later, used only for ajax.

**Comment by allenwq** [comment]
OK, I hope we do not duplicate these two logic too much.

**Comment by lowjoel** [comment]
I can't think of any offhand, take it as it comes? This part is completely new.

**Comment by allenwq** [comment]
Sure.

**Pull request merged**
