### PR TITLE
Persist workflow changes only after saving

### PR DESCRIPTION
**Pull request by lowjoel**
So we can use build() to create workflow-based objects. Also a bit closer to ActiveRecord behaviour.

### CODE REVIEW

**Comment by allenwq** [comment]
Want to document this somewhere? Other ppl probably won't know and may still think there is no need to save.

**Comment by lowjoel** [comment]
I do agree that workflow making persisting the workflow change by default to be counterintuitive, but where do we document this?

**Comment by allenwq** [comment]
We must document such things in some places? if I find the workflow state is not persisted after change, I'll think it's a issue of gem, highly unlikely I'll know that the extensions changed it.

**Comment by lowjoel** [comment]
Actually changing the workflow state should not persist the record. Changing the enum value does not persist the record. It's because of the workflow gem that does this.

Still, where do we want to document this?

**Comment by lowjoel** [comment]
Placed it in CONTRIBUTING.md...

**Comment by allenwq** [comment]
I agree, but from the gem documentation I won't know this, I would still expect the changes are persisted.

IDK, maybe put a message in the Gemfile, and the path to the extension ?

**Comment by lowjoel** [comment]
I think CONTRIBUTING is good enough. The Gemfile is verbose enough as it is.

**Comment by allenwq** [comment]
Okay, sure.

**Comment by lowjoel** [comment]
Should be good to go.

**Pull request merged**
