### PR TITLE
Bundle Update on 2016-11-06

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [addressable](https://github.com/sporkmonger/addressable), [2.4.0...2.5.0](https://github.com/sporkmonger/addressable/compare/addressable-2.4.0...addressable-2.5.0) ([CHANGELOG](https://github.com/sporkmonger/addressable/blob/master/CHANGELOG.md))
- Updated: [codeclimate-test-reporter](https://github.com/codeclimate/ruby-test-reporter), [0.6.0...1.0.0](https://github.com/codeclimate/ruby-test-reporter/compare/v0.6.0...v1.0.0)
- Updated: [i18n-tasks](https://github.com/glebm/i18n-tasks), [0.9.5...0.9.6](https://github.com/glebm/i18n-tasks/compare/v0.9.5...v0.9.6) ([CHANGELOG](https://github.com/glebm/i18n-tasks/blob/master/CHANGES.md))
- Updated: [nokogumbo](https://github.com/rubys/nokogumbo), [1.4.9...1.4.10](https://github.com/rubys/nokogumbo/compare/v1.4.9...v1.4.10)
- Updated: [summernote-rails](https://github.com/summernote/summernote-rails), [0.8.1.1...0.8.2.0](https://github.com/summernote/summernote-rails/compare/v0.8.1.1...v0.8.2.0) ([CHANGELOG](https://github.com/summernote/summernote-rails/releases))
- Added: [public_suffix](http://github.com/weppos/publicsuffix-ruby), [2.0.3](https://github.com/weppos/publicsuffix-ruby/tree/v2.0.3)

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
91 Pull Requests sent and 9 hours, 39 minutes, and 53 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by weiqingtoh** [comment]
Have added commit to fix configuration changes (which were breaking) for codeclimate-test-reporter. 

Some other specs broke during this update. To investigate.

**Comment by kxmbrian** [comment]
The summernote update is breaking the specs. Applied the fix from [this issue](https://github.com/summernote/summernote-rails/issues/48). It is not the ideal solution, but we'll need time if we want to dig deeper. 

I moved calls to the spec helper `fill_in_summernote` out of `within` blocks because it doesn't take into account the current scope, but searches the whole page for the summernote-d input. (I don't think it is worth the extra complexity of detecting the current scope)

**Comment by weiqingtoh** [comment]
@allenwq what do you think of the fix for summernote?

**Comment by allenwq** [comment]
Have discussed with Brian, I am OK with this fix. But seems coverall is not working ?

**Comment by weiqingtoh** [comment]
I'm not sure whether there are any configuration changes - but when I shifted the commits into a separate PR, it seems to report coverage >_< => https://github.com/Coursemology/coursemology2/pull/1672

**Comment by allenwq** [comment]
OK, so this should be random

**Pull request merged**
