### PR TITLE
Bundle Update on 2016-04-03

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [carrierwave](https://github.com/carrierwaveuploader/carrierwave), [f0c06c0...a020315](https://github.com/carrierwaveuploader/carrierwave/compare/f0c06c04de6ceda30f1a1627d21394f70359606b...a0203154ced699fd727b80483dec0855a8a75b69) ([CHANGELOG](https://github.com/carrierwaveuploader/carrierwave/blob/master/History.md))
- Updated: [autoprefixer-rails](https://github.com/ai/autoprefixer-rails), [6.3.5...6.3.6](https://github.com/ai/autoprefixer-rails/compare/6.3.5...6.3.6) ([CHANGELOG](https://github.com/ai/autoprefixer-rails/blob/master/CHANGELOG.md))
- Updated: [coursemology-polyglot](https://github.com/Coursemology/polyglot), [0.2.0...0.2.2](https://github.com/Coursemology/polyglot/compare/v0.2.0...v0.2.2) ([CHANGELOG](https://github.com/Coursemology/polyglot/releases))
- Updated: [request_store](http://github.com/steveklabnik/request_store), [1.3.0...1.3.1](https://github.com/steveklabnik/request_store/compare/v1.3.0...v1.3.1)

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Security and Dependency Updates
40 Pull Requests sent and 4 hours, 16 minutes, and 26 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by lowjoel** [comment]
@allenwq do you want to have a look at this?

**Comment by lowjoel** [comment]
@allenwq I'll merge this first because I need coursemology-polyglot@0.2.2. CarrierWave just released a new version of the gem, can you help update?

**Comment by allenwq** [comment]
@lowjoel The changes in carrierwave are related to specs refactoring, do we need to update anything ?

**Comment by lowjoel** [comment]
When I upgraded the gem version the specs actually broke.

**Comment by allenwq** [comment]
Might be a random failure? I'll keep tracking it.

**Comment by lowjoel** [comment]
Yeah, might want to manually check that.

All the Travis builds failed though.

**Pull request merged**
