### PR TITLE
Improve lesson plan edit page

### PR DESCRIPTION
**Pull request by kxmbrian**
- Allow copy and pasting of dates
- Shift bonus and end dates when start date is shifted
- Improve feedback when updating

Depends on #1917

### CODE REVIEW

**Comment by allenwq** [comment]
@kxmbrian Seems the request still sends to backend even when there's no change in the date, and the UI stop responding for a while after focus and un-focus.

**Comment by kxmbrian** [comment]
> Seems the request still sends to backend even when there's no change in the date
Fixed!

> the UI stop responding for a while after focus and un-focus.
There is still a little lag. Okay to leave this until I refactor lesson plan for performance after I'm done with survey?

**Comment by allenwq** [comment]
@kxmbrian BTW, the edit page breaks after survey is added, the survey partial is not implemented.

**Comment by kxmbrian** [comment]
yes, I will add it soon

**Pull request merged**
