### PR TITLE
Muzzled...

### PR DESCRIPTION
**Pull request by jsyeo**
:+1: Good to merge
lol

### CODE REVIEW

**Comment by jsyeo** [comment]
@lowjoel this should fix it. Took me one whole morning... zzz

**Comment by lowjoel** [comment]
You mean Hound happily ignores configuration that happens inside a hash? Is it a problem with the way they merge their config?

**Comment by jsyeo** [comment]
Maybe... Didn't have the time to verify this. :confounded:

**Comment by jsyeo** [comment]
The nation and its future needs me. lol

**Pull request merged**
