### PR TITLE
Add Python3.9 evaluator

### PR DESCRIPTION
**Pull request by cysjonathan**
support PIL, numpy, scipy, matplotlib
pandas, sklearn, networkx, fnss
torch, torchvision

### CODE REVIEW

**Comment by cysjonathan** [comment]
This PR is on request of Raj Joshi on behalf of CS5229

Two new python libraries included in the py3.9 evaluator:
- networkx
- fnss

**Comment by zhuhanming** [comment]
Are there tests written for languages supported? Would be good if we can add tests for this change.

**Comment by cysjonathan** [comment]
Nope there were never tests written for languages, although I think if we do, would it be better to write the tests in the evaluator repository? By the way this needs to be merged in.

**Comment by zhuhanming** [comment]
Do you mind rebasing this PR?

**Pull request merged**
