### PR TITLE
Check if sidekiq is defined before using it

### PR DESCRIPTION
**Pull request by jsyeo**

### CODE REVIEW

**Comment by jsyeo** [comment]
gif

**Comment by fonglh** [comment]
This is deliberate so you will consider how to run the consolidated email job.

https://github.com/Coursemology/coursemology2/pull/2787/commits/f8e833a9d11c1da0549eeca2edb83521d09faa9e

**Comment by jsyeo** [comment]
A nasty constant not found error isn't desirable. Especially if it's not in
your Gemfile. I thought it would default to using background jobs to do
this?

**Comment by fonglh** [comment]
No, the consolidated email job needs to be invoked hourly and does not happen automatically. Thus for a production deployment, a decision must be made on how to do this.

1. Use Sidekiq and Sidekiq-Cron as suggested [in the readme](https://github.com/coursemology/coursemology2#opening-reminder-emails). A conscious decision must be made to start the Sidekiq process in addition to the Rails server.

1. Run a system cron job to invoke the job. This requires system configuration that Coursemology cannot do for you.

1. Delete the initializer and not have opening reminders sent at all. We should not do this by default on behalf of the deployer.

At the time, we could not come up with any way to ensure correct behaviour by default. It was decided that it's better to fail fast and loud to force a decision rather than pretend everything is fine and fail silently by not sending the opening reminder emails.

**Pull request closed without merging**
